syntax = "proto3";

option java_package = "com.whk.protobuf.message";
option java_outer_classname = "MSGIDProto";

enum MSGID
{
  // data server
  LoginProto_LoginReq = 0;
  CreatePlayerProto_CreatePlayer = 1;
  PlayerInfoProto_ReqPlayerLogin = 2;
  PlayerInfoProto_TestMessage = 3;
  PlayerInfoProto_ReqPlayers = 4;
  SceneProto_ReqEnterScene = 5;
  PlayerInfoProto_PlayerInfos = 6;
  TipsProto_Tips = 7;
  LoginProto_LoginRes = 8;
  SceneProto_ResEnterScene = 9;
  PlayerInfoProto_ReqLevelUp = 100;

  // scene server
  SkillProto_ReqReleaseSkill = 102;
  SceneProto_SceneMessage = 103;


}