syntax = "proto3";

option java_package = "com.whk.protobuf.message";
option java_outer_classname = "MSGIDProto";

enum MSGID
{
  // gate server
  gate_server = 0;
  LoginProto_ReqLogin = 10;
  CreatePlayerProto_CreatePlayer = 11;
  PlayerInfoProto_ReqPlayerLogin = 12;
  PlayerInfoProto_TestMessage = 13;
  PlayerInfoProto_ReqPlayers = 14;
  SceneProto_ReqEnterScene = 15;
  PlayerInfoProto_PlayerInfos = 16;
  TipsProto_Tips = 17;
  LoginProto_ResLogin = 18;
  SceneProto_ResEnterScene = 19;
  CreatePlayerProto_ResCreatePlayer = 20;
  PlayerInfoProto_ResPlayerLogin = 21;

  // game server
  game_server = 1;
  PlayerInfoProto_ReqLevelUp = 100;
  PlayerInfoProto_ResLevelUp = 101;

  // scene server
  scene_server = 2;
  SkillProto_ReqReleaseSkill = 102;
  SceneProto_SceneMessage = 103;
  SceneProto_ReqPlayerMove = 104;
  SceneProto_ResPlayerMove = 105;
  SceneProto_ResRemoveView = 106;
  SceneProto_ResEnterView = 107;


}