syntax = "proto3";

option java_package = "com.whk.protobuf.message";
option java_outer_classname = "PlayerInfoProto";

message PlayerInfo{
  int64 id = 1;
  int64 userId = 2;
  int32 career = 3;
  int32 sex = 4;
  int64 lastLogin = 5;
  string name = 6;
  int32 level = 7;
}

message PlayerInfos{
  repeated PlayerInfo PlayerInfos = 1;
}

message ReqPlayerLogin{
  int64 playerId = 1;
}

message ResPlayerLogin{
  PlayerSimpleInfo info = 1;
}

message PlayerSimpleInfo {
  int64 playerId = 1; //角色ID
  string name = 2; //名称
  int32 level = 3; //等级
  int64 exp = 4; //经验
  int32 career = 5; //职业
  int32 sex = 6; //性别
  bool online = 7; //在线
  int64 createTime = 8;//創建時間
  int64 serverId = 9;//区服id
  int32 mapId = 10;//当前地图id
}

message ReqPlayers{

}

message TestMessage{
  string msg = 1;
}

message ReqLevelUp{

}

message ResLevelUp{
  int32 level = 1;
}