syntax = "proto3";
import "PlayerInfo.proto";

option java_package = "com.whk.protobuf.message";
option java_outer_classname = "SceneProto";

message ReqEnterScene{
  int32 mapId = 1;
  int32 line = 2;
}

message ResEnterScene{
  string desc = 1;
}

message SceneMessage{
  string desc = 1;
}

message ReqPlayerMove{
  float x = 1;
  float y = 2;
  float z = 3;
  float dir = 4;
}

message ResPlayerMove{
  float x = 1;
  float y = 2;
  float z = 3;
  float dir = 4;
  int64 playerId = 5;
}

message ResRemoveView{
  int64 playerId = 1;
}

message ResEnterView{
  ResPlayerMove move = 1;
  PlayerSimpleInfo simpleInfo = 2;
}