// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Message.proto
// Protobuf Java Version: 4.27.1

package org.whk.protobuf.message;

public final class MessageProto {
  private MessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      MessageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 command = 1;</code>
     * @return The command.
     */
    int getCommand();

    /**
     * <code>.LoginRes loginRes = 10;</code>
     * @return Whether the loginRes field is set.
     */
    boolean hasLoginRes();
    /**
     * <code>.LoginRes loginRes = 10;</code>
     * @return The loginRes.
     */
    org.whk.protobuf.message.LoginProto.LoginRes getLoginRes();
    /**
     * <code>.LoginRes loginRes = 10;</code>
     */
    org.whk.protobuf.message.LoginProto.LoginResOrBuilder getLoginResOrBuilder();

    /**
     * <code>.LoginReq loginReq = 11;</code>
     * @return Whether the loginReq field is set.
     */
    boolean hasLoginReq();
    /**
     * <code>.LoginReq loginReq = 11;</code>
     * @return The loginReq.
     */
    org.whk.protobuf.message.LoginProto.LoginReq getLoginReq();
    /**
     * <code>.LoginReq loginReq = 11;</code>
     */
    org.whk.protobuf.message.LoginProto.LoginReqOrBuilder getLoginReqOrBuilder();

    /**
     * <code>.Empty empty = 12;</code>
     * @return Whether the empty field is set.
     */
    boolean hasEmpty();
    /**
     * <code>.Empty empty = 12;</code>
     * @return The empty.
     */
    org.whk.protobuf.message.EmptyProto.Empty getEmpty();
    /**
     * <code>.Empty empty = 12;</code>
     */
    org.whk.protobuf.message.EmptyProto.EmptyOrBuilder getEmptyOrBuilder();

    /**
     * <code>.Tips tips = 13;</code>
     * @return Whether the tips field is set.
     */
    boolean hasTips();
    /**
     * <code>.Tips tips = 13;</code>
     * @return The tips.
     */
    org.whk.protobuf.message.TipsProto.Tips getTips();
    /**
     * <code>.Tips tips = 13;</code>
     */
    org.whk.protobuf.message.TipsProto.TipsOrBuilder getTipsOrBuilder();

    /**
     * <code>.PlayerInfos playerInfos = 14;</code>
     * @return Whether the playerInfos field is set.
     */
    boolean hasPlayerInfos();
    /**
     * <code>.PlayerInfos playerInfos = 14;</code>
     * @return The playerInfos.
     */
    org.whk.protobuf.message.PlayerInfoProto.PlayerInfos getPlayerInfos();
    /**
     * <code>.PlayerInfos playerInfos = 14;</code>
     */
    org.whk.protobuf.message.PlayerInfoProto.PlayerInfosOrBuilder getPlayerInfosOrBuilder();

    /**
     * <code>.CreatePlayer createPlayer = 15;</code>
     * @return Whether the createPlayer field is set.
     */
    boolean hasCreatePlayer();
    /**
     * <code>.CreatePlayer createPlayer = 15;</code>
     * @return The createPlayer.
     */
    org.whk.protobuf.message.CreatePlayerProto.CreatePlayer getCreatePlayer();
    /**
     * <code>.CreatePlayer createPlayer = 15;</code>
     */
    org.whk.protobuf.message.CreatePlayerProto.CreatePlayerOrBuilder getCreatePlayerOrBuilder();

    org.whk.protobuf.message.MessageProto.Message.BodyCase getBodyCase();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        Message.class.getName());
    }
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Message() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whk.protobuf.message.MessageProto.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whk.protobuf.message.MessageProto.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whk.protobuf.message.MessageProto.Message.class, org.whk.protobuf.message.MessageProto.Message.Builder.class);
    }

    private int bodyCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      LOGINRES(10),
      LOGINREQ(11),
      EMPTY(12),
      TIPS(13),
      PLAYERINFOS(14),
      CREATEPLAYER(15),
      BODY_NOT_SET(0);
      private final int value;
      private BodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static BodyCase forNumber(int value) {
        switch (value) {
          case 10: return LOGINRES;
          case 11: return LOGINREQ;
          case 12: return EMPTY;
          case 13: return TIPS;
          case 14: return PLAYERINFOS;
          case 15: return CREATEPLAYER;
          case 0: return BODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_ = 0;
    /**
     * <code>int32 command = 1;</code>
     * @return The command.
     */
    @java.lang.Override
    public int getCommand() {
      return command_;
    }

    public static final int LOGINRES_FIELD_NUMBER = 10;
    /**
     * <code>.LoginRes loginRes = 10;</code>
     * @return Whether the loginRes field is set.
     */
    @java.lang.Override
    public boolean hasLoginRes() {
      return bodyCase_ == 10;
    }
    /**
     * <code>.LoginRes loginRes = 10;</code>
     * @return The loginRes.
     */
    @java.lang.Override
    public org.whk.protobuf.message.LoginProto.LoginRes getLoginRes() {
      if (bodyCase_ == 10) {
         return (org.whk.protobuf.message.LoginProto.LoginRes) body_;
      }
      return org.whk.protobuf.message.LoginProto.LoginRes.getDefaultInstance();
    }
    /**
     * <code>.LoginRes loginRes = 10;</code>
     */
    @java.lang.Override
    public org.whk.protobuf.message.LoginProto.LoginResOrBuilder getLoginResOrBuilder() {
      if (bodyCase_ == 10) {
         return (org.whk.protobuf.message.LoginProto.LoginRes) body_;
      }
      return org.whk.protobuf.message.LoginProto.LoginRes.getDefaultInstance();
    }

    public static final int LOGINREQ_FIELD_NUMBER = 11;
    /**
     * <code>.LoginReq loginReq = 11;</code>
     * @return Whether the loginReq field is set.
     */
    @java.lang.Override
    public boolean hasLoginReq() {
      return bodyCase_ == 11;
    }
    /**
     * <code>.LoginReq loginReq = 11;</code>
     * @return The loginReq.
     */
    @java.lang.Override
    public org.whk.protobuf.message.LoginProto.LoginReq getLoginReq() {
      if (bodyCase_ == 11) {
         return (org.whk.protobuf.message.LoginProto.LoginReq) body_;
      }
      return org.whk.protobuf.message.LoginProto.LoginReq.getDefaultInstance();
    }
    /**
     * <code>.LoginReq loginReq = 11;</code>
     */
    @java.lang.Override
    public org.whk.protobuf.message.LoginProto.LoginReqOrBuilder getLoginReqOrBuilder() {
      if (bodyCase_ == 11) {
         return (org.whk.protobuf.message.LoginProto.LoginReq) body_;
      }
      return org.whk.protobuf.message.LoginProto.LoginReq.getDefaultInstance();
    }

    public static final int EMPTY_FIELD_NUMBER = 12;
    /**
     * <code>.Empty empty = 12;</code>
     * @return Whether the empty field is set.
     */
    @java.lang.Override
    public boolean hasEmpty() {
      return bodyCase_ == 12;
    }
    /**
     * <code>.Empty empty = 12;</code>
     * @return The empty.
     */
    @java.lang.Override
    public org.whk.protobuf.message.EmptyProto.Empty getEmpty() {
      if (bodyCase_ == 12) {
         return (org.whk.protobuf.message.EmptyProto.Empty) body_;
      }
      return org.whk.protobuf.message.EmptyProto.Empty.getDefaultInstance();
    }
    /**
     * <code>.Empty empty = 12;</code>
     */
    @java.lang.Override
    public org.whk.protobuf.message.EmptyProto.EmptyOrBuilder getEmptyOrBuilder() {
      if (bodyCase_ == 12) {
         return (org.whk.protobuf.message.EmptyProto.Empty) body_;
      }
      return org.whk.protobuf.message.EmptyProto.Empty.getDefaultInstance();
    }

    public static final int TIPS_FIELD_NUMBER = 13;
    /**
     * <code>.Tips tips = 13;</code>
     * @return Whether the tips field is set.
     */
    @java.lang.Override
    public boolean hasTips() {
      return bodyCase_ == 13;
    }
    /**
     * <code>.Tips tips = 13;</code>
     * @return The tips.
     */
    @java.lang.Override
    public org.whk.protobuf.message.TipsProto.Tips getTips() {
      if (bodyCase_ == 13) {
         return (org.whk.protobuf.message.TipsProto.Tips) body_;
      }
      return org.whk.protobuf.message.TipsProto.Tips.getDefaultInstance();
    }
    /**
     * <code>.Tips tips = 13;</code>
     */
    @java.lang.Override
    public org.whk.protobuf.message.TipsProto.TipsOrBuilder getTipsOrBuilder() {
      if (bodyCase_ == 13) {
         return (org.whk.protobuf.message.TipsProto.Tips) body_;
      }
      return org.whk.protobuf.message.TipsProto.Tips.getDefaultInstance();
    }

    public static final int PLAYERINFOS_FIELD_NUMBER = 14;
    /**
     * <code>.PlayerInfos playerInfos = 14;</code>
     * @return Whether the playerInfos field is set.
     */
    @java.lang.Override
    public boolean hasPlayerInfos() {
      return bodyCase_ == 14;
    }
    /**
     * <code>.PlayerInfos playerInfos = 14;</code>
     * @return The playerInfos.
     */
    @java.lang.Override
    public org.whk.protobuf.message.PlayerInfoProto.PlayerInfos getPlayerInfos() {
      if (bodyCase_ == 14) {
         return (org.whk.protobuf.message.PlayerInfoProto.PlayerInfos) body_;
      }
      return org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.getDefaultInstance();
    }
    /**
     * <code>.PlayerInfos playerInfos = 14;</code>
     */
    @java.lang.Override
    public org.whk.protobuf.message.PlayerInfoProto.PlayerInfosOrBuilder getPlayerInfosOrBuilder() {
      if (bodyCase_ == 14) {
         return (org.whk.protobuf.message.PlayerInfoProto.PlayerInfos) body_;
      }
      return org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.getDefaultInstance();
    }

    public static final int CREATEPLAYER_FIELD_NUMBER = 15;
    /**
     * <code>.CreatePlayer createPlayer = 15;</code>
     * @return Whether the createPlayer field is set.
     */
    @java.lang.Override
    public boolean hasCreatePlayer() {
      return bodyCase_ == 15;
    }
    /**
     * <code>.CreatePlayer createPlayer = 15;</code>
     * @return The createPlayer.
     */
    @java.lang.Override
    public org.whk.protobuf.message.CreatePlayerProto.CreatePlayer getCreatePlayer() {
      if (bodyCase_ == 15) {
         return (org.whk.protobuf.message.CreatePlayerProto.CreatePlayer) body_;
      }
      return org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.getDefaultInstance();
    }
    /**
     * <code>.CreatePlayer createPlayer = 15;</code>
     */
    @java.lang.Override
    public org.whk.protobuf.message.CreatePlayerProto.CreatePlayerOrBuilder getCreatePlayerOrBuilder() {
      if (bodyCase_ == 15) {
         return (org.whk.protobuf.message.CreatePlayerProto.CreatePlayer) body_;
      }
      return org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (command_ != 0) {
        output.writeInt32(1, command_);
      }
      if (bodyCase_ == 10) {
        output.writeMessage(10, (org.whk.protobuf.message.LoginProto.LoginRes) body_);
      }
      if (bodyCase_ == 11) {
        output.writeMessage(11, (org.whk.protobuf.message.LoginProto.LoginReq) body_);
      }
      if (bodyCase_ == 12) {
        output.writeMessage(12, (org.whk.protobuf.message.EmptyProto.Empty) body_);
      }
      if (bodyCase_ == 13) {
        output.writeMessage(13, (org.whk.protobuf.message.TipsProto.Tips) body_);
      }
      if (bodyCase_ == 14) {
        output.writeMessage(14, (org.whk.protobuf.message.PlayerInfoProto.PlayerInfos) body_);
      }
      if (bodyCase_ == 15) {
        output.writeMessage(15, (org.whk.protobuf.message.CreatePlayerProto.CreatePlayer) body_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (command_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, command_);
      }
      if (bodyCase_ == 10) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, (org.whk.protobuf.message.LoginProto.LoginRes) body_);
      }
      if (bodyCase_ == 11) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, (org.whk.protobuf.message.LoginProto.LoginReq) body_);
      }
      if (bodyCase_ == 12) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, (org.whk.protobuf.message.EmptyProto.Empty) body_);
      }
      if (bodyCase_ == 13) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, (org.whk.protobuf.message.TipsProto.Tips) body_);
      }
      if (bodyCase_ == 14) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, (org.whk.protobuf.message.PlayerInfoProto.PlayerInfos) body_);
      }
      if (bodyCase_ == 15) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, (org.whk.protobuf.message.CreatePlayerProto.CreatePlayer) body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.whk.protobuf.message.MessageProto.Message)) {
        return super.equals(obj);
      }
      org.whk.protobuf.message.MessageProto.Message other = (org.whk.protobuf.message.MessageProto.Message) obj;

      if (getCommand()
          != other.getCommand()) return false;
      if (!getBodyCase().equals(other.getBodyCase())) return false;
      switch (bodyCase_) {
        case 10:
          if (!getLoginRes()
              .equals(other.getLoginRes())) return false;
          break;
        case 11:
          if (!getLoginReq()
              .equals(other.getLoginReq())) return false;
          break;
        case 12:
          if (!getEmpty()
              .equals(other.getEmpty())) return false;
          break;
        case 13:
          if (!getTips()
              .equals(other.getTips())) return false;
          break;
        case 14:
          if (!getPlayerInfos()
              .equals(other.getPlayerInfos())) return false;
          break;
        case 15:
          if (!getCreatePlayer()
              .equals(other.getCreatePlayer())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand();
      switch (bodyCase_) {
        case 10:
          hash = (37 * hash) + LOGINRES_FIELD_NUMBER;
          hash = (53 * hash) + getLoginRes().hashCode();
          break;
        case 11:
          hash = (37 * hash) + LOGINREQ_FIELD_NUMBER;
          hash = (53 * hash) + getLoginReq().hashCode();
          break;
        case 12:
          hash = (37 * hash) + EMPTY_FIELD_NUMBER;
          hash = (53 * hash) + getEmpty().hashCode();
          break;
        case 13:
          hash = (37 * hash) + TIPS_FIELD_NUMBER;
          hash = (53 * hash) + getTips().hashCode();
          break;
        case 14:
          hash = (37 * hash) + PLAYERINFOS_FIELD_NUMBER;
          hash = (53 * hash) + getPlayerInfos().hashCode();
          break;
        case 15:
          hash = (37 * hash) + CREATEPLAYER_FIELD_NUMBER;
          hash = (53 * hash) + getCreatePlayer().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.whk.protobuf.message.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whk.protobuf.message.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whk.protobuf.message.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whk.protobuf.message.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whk.protobuf.message.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whk.protobuf.message.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whk.protobuf.message.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.whk.protobuf.message.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.whk.protobuf.message.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.whk.protobuf.message.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.whk.protobuf.message.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.whk.protobuf.message.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.whk.protobuf.message.MessageProto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        org.whk.protobuf.message.MessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.whk.protobuf.message.MessageProto.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.whk.protobuf.message.MessageProto.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.whk.protobuf.message.MessageProto.Message.class, org.whk.protobuf.message.MessageProto.Message.Builder.class);
      }

      // Construct using org.whk.protobuf.message.MessageProto.Message.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        command_ = 0;
        if (loginResBuilder_ != null) {
          loginResBuilder_.clear();
        }
        if (loginReqBuilder_ != null) {
          loginReqBuilder_.clear();
        }
        if (emptyBuilder_ != null) {
          emptyBuilder_.clear();
        }
        if (tipsBuilder_ != null) {
          tipsBuilder_.clear();
        }
        if (playerInfosBuilder_ != null) {
          playerInfosBuilder_.clear();
        }
        if (createPlayerBuilder_ != null) {
          createPlayerBuilder_.clear();
        }
        bodyCase_ = 0;
        body_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.whk.protobuf.message.MessageProto.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public org.whk.protobuf.message.MessageProto.Message getDefaultInstanceForType() {
        return org.whk.protobuf.message.MessageProto.Message.getDefaultInstance();
      }

      @java.lang.Override
      public org.whk.protobuf.message.MessageProto.Message build() {
        org.whk.protobuf.message.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.whk.protobuf.message.MessageProto.Message buildPartial() {
        org.whk.protobuf.message.MessageProto.Message result = new org.whk.protobuf.message.MessageProto.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(org.whk.protobuf.message.MessageProto.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.command_ = command_;
        }
      }

      private void buildPartialOneofs(org.whk.protobuf.message.MessageProto.Message result) {
        result.bodyCase_ = bodyCase_;
        result.body_ = this.body_;
        if (bodyCase_ == 10 &&
            loginResBuilder_ != null) {
          result.body_ = loginResBuilder_.build();
        }
        if (bodyCase_ == 11 &&
            loginReqBuilder_ != null) {
          result.body_ = loginReqBuilder_.build();
        }
        if (bodyCase_ == 12 &&
            emptyBuilder_ != null) {
          result.body_ = emptyBuilder_.build();
        }
        if (bodyCase_ == 13 &&
            tipsBuilder_ != null) {
          result.body_ = tipsBuilder_.build();
        }
        if (bodyCase_ == 14 &&
            playerInfosBuilder_ != null) {
          result.body_ = playerInfosBuilder_.build();
        }
        if (bodyCase_ == 15 &&
            createPlayerBuilder_ != null) {
          result.body_ = createPlayerBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.whk.protobuf.message.MessageProto.Message) {
          return mergeFrom((org.whk.protobuf.message.MessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.whk.protobuf.message.MessageProto.Message other) {
        if (other == org.whk.protobuf.message.MessageProto.Message.getDefaultInstance()) return this;
        if (other.getCommand() != 0) {
          setCommand(other.getCommand());
        }
        switch (other.getBodyCase()) {
          case LOGINRES: {
            mergeLoginRes(other.getLoginRes());
            break;
          }
          case LOGINREQ: {
            mergeLoginReq(other.getLoginReq());
            break;
          }
          case EMPTY: {
            mergeEmpty(other.getEmpty());
            break;
          }
          case TIPS: {
            mergeTips(other.getTips());
            break;
          }
          case PLAYERINFOS: {
            mergePlayerInfos(other.getPlayerInfos());
            break;
          }
          case CREATEPLAYER: {
            mergeCreatePlayer(other.getCreatePlayer());
            break;
          }
          case BODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                command_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 82: {
                input.readMessage(
                    getLoginResFieldBuilder().getBuilder(),
                    extensionRegistry);
                bodyCase_ = 10;
                break;
              } // case 82
              case 90: {
                input.readMessage(
                    getLoginReqFieldBuilder().getBuilder(),
                    extensionRegistry);
                bodyCase_ = 11;
                break;
              } // case 90
              case 98: {
                input.readMessage(
                    getEmptyFieldBuilder().getBuilder(),
                    extensionRegistry);
                bodyCase_ = 12;
                break;
              } // case 98
              case 106: {
                input.readMessage(
                    getTipsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bodyCase_ = 13;
                break;
              } // case 106
              case 114: {
                input.readMessage(
                    getPlayerInfosFieldBuilder().getBuilder(),
                    extensionRegistry);
                bodyCase_ = 14;
                break;
              } // case 114
              case 122: {
                input.readMessage(
                    getCreatePlayerFieldBuilder().getBuilder(),
                    extensionRegistry);
                bodyCase_ = 15;
                break;
              } // case 122
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bodyCase_ = 0;
      private java.lang.Object body_;
      public BodyCase
          getBodyCase() {
        return BodyCase.forNumber(
            bodyCase_);
      }

      public Builder clearBody() {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int command_ ;
      /**
       * <code>int32 command = 1;</code>
       * @return The command.
       */
      @java.lang.Override
      public int getCommand() {
        return command_;
      }
      /**
       * <code>int32 command = 1;</code>
       * @param value The command to set.
       * @return This builder for chaining.
       */
      public Builder setCommand(int value) {

        command_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 command = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.LoginProto.LoginRes, org.whk.protobuf.message.LoginProto.LoginRes.Builder, org.whk.protobuf.message.LoginProto.LoginResOrBuilder> loginResBuilder_;
      /**
       * <code>.LoginRes loginRes = 10;</code>
       * @return Whether the loginRes field is set.
       */
      @java.lang.Override
      public boolean hasLoginRes() {
        return bodyCase_ == 10;
      }
      /**
       * <code>.LoginRes loginRes = 10;</code>
       * @return The loginRes.
       */
      @java.lang.Override
      public org.whk.protobuf.message.LoginProto.LoginRes getLoginRes() {
        if (loginResBuilder_ == null) {
          if (bodyCase_ == 10) {
            return (org.whk.protobuf.message.LoginProto.LoginRes) body_;
          }
          return org.whk.protobuf.message.LoginProto.LoginRes.getDefaultInstance();
        } else {
          if (bodyCase_ == 10) {
            return loginResBuilder_.getMessage();
          }
          return org.whk.protobuf.message.LoginProto.LoginRes.getDefaultInstance();
        }
      }
      /**
       * <code>.LoginRes loginRes = 10;</code>
       */
      public Builder setLoginRes(org.whk.protobuf.message.LoginProto.LoginRes value) {
        if (loginResBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          loginResBuilder_.setMessage(value);
        }
        bodyCase_ = 10;
        return this;
      }
      /**
       * <code>.LoginRes loginRes = 10;</code>
       */
      public Builder setLoginRes(
          org.whk.protobuf.message.LoginProto.LoginRes.Builder builderForValue) {
        if (loginResBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          loginResBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 10;
        return this;
      }
      /**
       * <code>.LoginRes loginRes = 10;</code>
       */
      public Builder mergeLoginRes(org.whk.protobuf.message.LoginProto.LoginRes value) {
        if (loginResBuilder_ == null) {
          if (bodyCase_ == 10 &&
              body_ != org.whk.protobuf.message.LoginProto.LoginRes.getDefaultInstance()) {
            body_ = org.whk.protobuf.message.LoginProto.LoginRes.newBuilder((org.whk.protobuf.message.LoginProto.LoginRes) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 10) {
            loginResBuilder_.mergeFrom(value);
          } else {
            loginResBuilder_.setMessage(value);
          }
        }
        bodyCase_ = 10;
        return this;
      }
      /**
       * <code>.LoginRes loginRes = 10;</code>
       */
      public Builder clearLoginRes() {
        if (loginResBuilder_ == null) {
          if (bodyCase_ == 10) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 10) {
            bodyCase_ = 0;
            body_ = null;
          }
          loginResBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.LoginRes loginRes = 10;</code>
       */
      public org.whk.protobuf.message.LoginProto.LoginRes.Builder getLoginResBuilder() {
        return getLoginResFieldBuilder().getBuilder();
      }
      /**
       * <code>.LoginRes loginRes = 10;</code>
       */
      @java.lang.Override
      public org.whk.protobuf.message.LoginProto.LoginResOrBuilder getLoginResOrBuilder() {
        if ((bodyCase_ == 10) && (loginResBuilder_ != null)) {
          return loginResBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 10) {
            return (org.whk.protobuf.message.LoginProto.LoginRes) body_;
          }
          return org.whk.protobuf.message.LoginProto.LoginRes.getDefaultInstance();
        }
      }
      /**
       * <code>.LoginRes loginRes = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.LoginProto.LoginRes, org.whk.protobuf.message.LoginProto.LoginRes.Builder, org.whk.protobuf.message.LoginProto.LoginResOrBuilder> 
          getLoginResFieldBuilder() {
        if (loginResBuilder_ == null) {
          if (!(bodyCase_ == 10)) {
            body_ = org.whk.protobuf.message.LoginProto.LoginRes.getDefaultInstance();
          }
          loginResBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.whk.protobuf.message.LoginProto.LoginRes, org.whk.protobuf.message.LoginProto.LoginRes.Builder, org.whk.protobuf.message.LoginProto.LoginResOrBuilder>(
                  (org.whk.protobuf.message.LoginProto.LoginRes) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 10;
        onChanged();
        return loginResBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.LoginProto.LoginReq, org.whk.protobuf.message.LoginProto.LoginReq.Builder, org.whk.protobuf.message.LoginProto.LoginReqOrBuilder> loginReqBuilder_;
      /**
       * <code>.LoginReq loginReq = 11;</code>
       * @return Whether the loginReq field is set.
       */
      @java.lang.Override
      public boolean hasLoginReq() {
        return bodyCase_ == 11;
      }
      /**
       * <code>.LoginReq loginReq = 11;</code>
       * @return The loginReq.
       */
      @java.lang.Override
      public org.whk.protobuf.message.LoginProto.LoginReq getLoginReq() {
        if (loginReqBuilder_ == null) {
          if (bodyCase_ == 11) {
            return (org.whk.protobuf.message.LoginProto.LoginReq) body_;
          }
          return org.whk.protobuf.message.LoginProto.LoginReq.getDefaultInstance();
        } else {
          if (bodyCase_ == 11) {
            return loginReqBuilder_.getMessage();
          }
          return org.whk.protobuf.message.LoginProto.LoginReq.getDefaultInstance();
        }
      }
      /**
       * <code>.LoginReq loginReq = 11;</code>
       */
      public Builder setLoginReq(org.whk.protobuf.message.LoginProto.LoginReq value) {
        if (loginReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          loginReqBuilder_.setMessage(value);
        }
        bodyCase_ = 11;
        return this;
      }
      /**
       * <code>.LoginReq loginReq = 11;</code>
       */
      public Builder setLoginReq(
          org.whk.protobuf.message.LoginProto.LoginReq.Builder builderForValue) {
        if (loginReqBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          loginReqBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 11;
        return this;
      }
      /**
       * <code>.LoginReq loginReq = 11;</code>
       */
      public Builder mergeLoginReq(org.whk.protobuf.message.LoginProto.LoginReq value) {
        if (loginReqBuilder_ == null) {
          if (bodyCase_ == 11 &&
              body_ != org.whk.protobuf.message.LoginProto.LoginReq.getDefaultInstance()) {
            body_ = org.whk.protobuf.message.LoginProto.LoginReq.newBuilder((org.whk.protobuf.message.LoginProto.LoginReq) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 11) {
            loginReqBuilder_.mergeFrom(value);
          } else {
            loginReqBuilder_.setMessage(value);
          }
        }
        bodyCase_ = 11;
        return this;
      }
      /**
       * <code>.LoginReq loginReq = 11;</code>
       */
      public Builder clearLoginReq() {
        if (loginReqBuilder_ == null) {
          if (bodyCase_ == 11) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 11) {
            bodyCase_ = 0;
            body_ = null;
          }
          loginReqBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.LoginReq loginReq = 11;</code>
       */
      public org.whk.protobuf.message.LoginProto.LoginReq.Builder getLoginReqBuilder() {
        return getLoginReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.LoginReq loginReq = 11;</code>
       */
      @java.lang.Override
      public org.whk.protobuf.message.LoginProto.LoginReqOrBuilder getLoginReqOrBuilder() {
        if ((bodyCase_ == 11) && (loginReqBuilder_ != null)) {
          return loginReqBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 11) {
            return (org.whk.protobuf.message.LoginProto.LoginReq) body_;
          }
          return org.whk.protobuf.message.LoginProto.LoginReq.getDefaultInstance();
        }
      }
      /**
       * <code>.LoginReq loginReq = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.LoginProto.LoginReq, org.whk.protobuf.message.LoginProto.LoginReq.Builder, org.whk.protobuf.message.LoginProto.LoginReqOrBuilder> 
          getLoginReqFieldBuilder() {
        if (loginReqBuilder_ == null) {
          if (!(bodyCase_ == 11)) {
            body_ = org.whk.protobuf.message.LoginProto.LoginReq.getDefaultInstance();
          }
          loginReqBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.whk.protobuf.message.LoginProto.LoginReq, org.whk.protobuf.message.LoginProto.LoginReq.Builder, org.whk.protobuf.message.LoginProto.LoginReqOrBuilder>(
                  (org.whk.protobuf.message.LoginProto.LoginReq) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 11;
        onChanged();
        return loginReqBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.EmptyProto.Empty, org.whk.protobuf.message.EmptyProto.Empty.Builder, org.whk.protobuf.message.EmptyProto.EmptyOrBuilder> emptyBuilder_;
      /**
       * <code>.Empty empty = 12;</code>
       * @return Whether the empty field is set.
       */
      @java.lang.Override
      public boolean hasEmpty() {
        return bodyCase_ == 12;
      }
      /**
       * <code>.Empty empty = 12;</code>
       * @return The empty.
       */
      @java.lang.Override
      public org.whk.protobuf.message.EmptyProto.Empty getEmpty() {
        if (emptyBuilder_ == null) {
          if (bodyCase_ == 12) {
            return (org.whk.protobuf.message.EmptyProto.Empty) body_;
          }
          return org.whk.protobuf.message.EmptyProto.Empty.getDefaultInstance();
        } else {
          if (bodyCase_ == 12) {
            return emptyBuilder_.getMessage();
          }
          return org.whk.protobuf.message.EmptyProto.Empty.getDefaultInstance();
        }
      }
      /**
       * <code>.Empty empty = 12;</code>
       */
      public Builder setEmpty(org.whk.protobuf.message.EmptyProto.Empty value) {
        if (emptyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          emptyBuilder_.setMessage(value);
        }
        bodyCase_ = 12;
        return this;
      }
      /**
       * <code>.Empty empty = 12;</code>
       */
      public Builder setEmpty(
          org.whk.protobuf.message.EmptyProto.Empty.Builder builderForValue) {
        if (emptyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          emptyBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 12;
        return this;
      }
      /**
       * <code>.Empty empty = 12;</code>
       */
      public Builder mergeEmpty(org.whk.protobuf.message.EmptyProto.Empty value) {
        if (emptyBuilder_ == null) {
          if (bodyCase_ == 12 &&
              body_ != org.whk.protobuf.message.EmptyProto.Empty.getDefaultInstance()) {
            body_ = org.whk.protobuf.message.EmptyProto.Empty.newBuilder((org.whk.protobuf.message.EmptyProto.Empty) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 12) {
            emptyBuilder_.mergeFrom(value);
          } else {
            emptyBuilder_.setMessage(value);
          }
        }
        bodyCase_ = 12;
        return this;
      }
      /**
       * <code>.Empty empty = 12;</code>
       */
      public Builder clearEmpty() {
        if (emptyBuilder_ == null) {
          if (bodyCase_ == 12) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 12) {
            bodyCase_ = 0;
            body_ = null;
          }
          emptyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Empty empty = 12;</code>
       */
      public org.whk.protobuf.message.EmptyProto.Empty.Builder getEmptyBuilder() {
        return getEmptyFieldBuilder().getBuilder();
      }
      /**
       * <code>.Empty empty = 12;</code>
       */
      @java.lang.Override
      public org.whk.protobuf.message.EmptyProto.EmptyOrBuilder getEmptyOrBuilder() {
        if ((bodyCase_ == 12) && (emptyBuilder_ != null)) {
          return emptyBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 12) {
            return (org.whk.protobuf.message.EmptyProto.Empty) body_;
          }
          return org.whk.protobuf.message.EmptyProto.Empty.getDefaultInstance();
        }
      }
      /**
       * <code>.Empty empty = 12;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.EmptyProto.Empty, org.whk.protobuf.message.EmptyProto.Empty.Builder, org.whk.protobuf.message.EmptyProto.EmptyOrBuilder> 
          getEmptyFieldBuilder() {
        if (emptyBuilder_ == null) {
          if (!(bodyCase_ == 12)) {
            body_ = org.whk.protobuf.message.EmptyProto.Empty.getDefaultInstance();
          }
          emptyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.whk.protobuf.message.EmptyProto.Empty, org.whk.protobuf.message.EmptyProto.Empty.Builder, org.whk.protobuf.message.EmptyProto.EmptyOrBuilder>(
                  (org.whk.protobuf.message.EmptyProto.Empty) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 12;
        onChanged();
        return emptyBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.TipsProto.Tips, org.whk.protobuf.message.TipsProto.Tips.Builder, org.whk.protobuf.message.TipsProto.TipsOrBuilder> tipsBuilder_;
      /**
       * <code>.Tips tips = 13;</code>
       * @return Whether the tips field is set.
       */
      @java.lang.Override
      public boolean hasTips() {
        return bodyCase_ == 13;
      }
      /**
       * <code>.Tips tips = 13;</code>
       * @return The tips.
       */
      @java.lang.Override
      public org.whk.protobuf.message.TipsProto.Tips getTips() {
        if (tipsBuilder_ == null) {
          if (bodyCase_ == 13) {
            return (org.whk.protobuf.message.TipsProto.Tips) body_;
          }
          return org.whk.protobuf.message.TipsProto.Tips.getDefaultInstance();
        } else {
          if (bodyCase_ == 13) {
            return tipsBuilder_.getMessage();
          }
          return org.whk.protobuf.message.TipsProto.Tips.getDefaultInstance();
        }
      }
      /**
       * <code>.Tips tips = 13;</code>
       */
      public Builder setTips(org.whk.protobuf.message.TipsProto.Tips value) {
        if (tipsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          tipsBuilder_.setMessage(value);
        }
        bodyCase_ = 13;
        return this;
      }
      /**
       * <code>.Tips tips = 13;</code>
       */
      public Builder setTips(
          org.whk.protobuf.message.TipsProto.Tips.Builder builderForValue) {
        if (tipsBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          tipsBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 13;
        return this;
      }
      /**
       * <code>.Tips tips = 13;</code>
       */
      public Builder mergeTips(org.whk.protobuf.message.TipsProto.Tips value) {
        if (tipsBuilder_ == null) {
          if (bodyCase_ == 13 &&
              body_ != org.whk.protobuf.message.TipsProto.Tips.getDefaultInstance()) {
            body_ = org.whk.protobuf.message.TipsProto.Tips.newBuilder((org.whk.protobuf.message.TipsProto.Tips) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 13) {
            tipsBuilder_.mergeFrom(value);
          } else {
            tipsBuilder_.setMessage(value);
          }
        }
        bodyCase_ = 13;
        return this;
      }
      /**
       * <code>.Tips tips = 13;</code>
       */
      public Builder clearTips() {
        if (tipsBuilder_ == null) {
          if (bodyCase_ == 13) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 13) {
            bodyCase_ = 0;
            body_ = null;
          }
          tipsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Tips tips = 13;</code>
       */
      public org.whk.protobuf.message.TipsProto.Tips.Builder getTipsBuilder() {
        return getTipsFieldBuilder().getBuilder();
      }
      /**
       * <code>.Tips tips = 13;</code>
       */
      @java.lang.Override
      public org.whk.protobuf.message.TipsProto.TipsOrBuilder getTipsOrBuilder() {
        if ((bodyCase_ == 13) && (tipsBuilder_ != null)) {
          return tipsBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 13) {
            return (org.whk.protobuf.message.TipsProto.Tips) body_;
          }
          return org.whk.protobuf.message.TipsProto.Tips.getDefaultInstance();
        }
      }
      /**
       * <code>.Tips tips = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.TipsProto.Tips, org.whk.protobuf.message.TipsProto.Tips.Builder, org.whk.protobuf.message.TipsProto.TipsOrBuilder> 
          getTipsFieldBuilder() {
        if (tipsBuilder_ == null) {
          if (!(bodyCase_ == 13)) {
            body_ = org.whk.protobuf.message.TipsProto.Tips.getDefaultInstance();
          }
          tipsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.whk.protobuf.message.TipsProto.Tips, org.whk.protobuf.message.TipsProto.Tips.Builder, org.whk.protobuf.message.TipsProto.TipsOrBuilder>(
                  (org.whk.protobuf.message.TipsProto.Tips) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 13;
        onChanged();
        return tipsBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.PlayerInfoProto.PlayerInfos, org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.Builder, org.whk.protobuf.message.PlayerInfoProto.PlayerInfosOrBuilder> playerInfosBuilder_;
      /**
       * <code>.PlayerInfos playerInfos = 14;</code>
       * @return Whether the playerInfos field is set.
       */
      @java.lang.Override
      public boolean hasPlayerInfos() {
        return bodyCase_ == 14;
      }
      /**
       * <code>.PlayerInfos playerInfos = 14;</code>
       * @return The playerInfos.
       */
      @java.lang.Override
      public org.whk.protobuf.message.PlayerInfoProto.PlayerInfos getPlayerInfos() {
        if (playerInfosBuilder_ == null) {
          if (bodyCase_ == 14) {
            return (org.whk.protobuf.message.PlayerInfoProto.PlayerInfos) body_;
          }
          return org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.getDefaultInstance();
        } else {
          if (bodyCase_ == 14) {
            return playerInfosBuilder_.getMessage();
          }
          return org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.getDefaultInstance();
        }
      }
      /**
       * <code>.PlayerInfos playerInfos = 14;</code>
       */
      public Builder setPlayerInfos(org.whk.protobuf.message.PlayerInfoProto.PlayerInfos value) {
        if (playerInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          playerInfosBuilder_.setMessage(value);
        }
        bodyCase_ = 14;
        return this;
      }
      /**
       * <code>.PlayerInfos playerInfos = 14;</code>
       */
      public Builder setPlayerInfos(
          org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.Builder builderForValue) {
        if (playerInfosBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          playerInfosBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 14;
        return this;
      }
      /**
       * <code>.PlayerInfos playerInfos = 14;</code>
       */
      public Builder mergePlayerInfos(org.whk.protobuf.message.PlayerInfoProto.PlayerInfos value) {
        if (playerInfosBuilder_ == null) {
          if (bodyCase_ == 14 &&
              body_ != org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.getDefaultInstance()) {
            body_ = org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.newBuilder((org.whk.protobuf.message.PlayerInfoProto.PlayerInfos) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 14) {
            playerInfosBuilder_.mergeFrom(value);
          } else {
            playerInfosBuilder_.setMessage(value);
          }
        }
        bodyCase_ = 14;
        return this;
      }
      /**
       * <code>.PlayerInfos playerInfos = 14;</code>
       */
      public Builder clearPlayerInfos() {
        if (playerInfosBuilder_ == null) {
          if (bodyCase_ == 14) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 14) {
            bodyCase_ = 0;
            body_ = null;
          }
          playerInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.PlayerInfos playerInfos = 14;</code>
       */
      public org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.Builder getPlayerInfosBuilder() {
        return getPlayerInfosFieldBuilder().getBuilder();
      }
      /**
       * <code>.PlayerInfos playerInfos = 14;</code>
       */
      @java.lang.Override
      public org.whk.protobuf.message.PlayerInfoProto.PlayerInfosOrBuilder getPlayerInfosOrBuilder() {
        if ((bodyCase_ == 14) && (playerInfosBuilder_ != null)) {
          return playerInfosBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 14) {
            return (org.whk.protobuf.message.PlayerInfoProto.PlayerInfos) body_;
          }
          return org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.getDefaultInstance();
        }
      }
      /**
       * <code>.PlayerInfos playerInfos = 14;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.PlayerInfoProto.PlayerInfos, org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.Builder, org.whk.protobuf.message.PlayerInfoProto.PlayerInfosOrBuilder> 
          getPlayerInfosFieldBuilder() {
        if (playerInfosBuilder_ == null) {
          if (!(bodyCase_ == 14)) {
            body_ = org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.getDefaultInstance();
          }
          playerInfosBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.whk.protobuf.message.PlayerInfoProto.PlayerInfos, org.whk.protobuf.message.PlayerInfoProto.PlayerInfos.Builder, org.whk.protobuf.message.PlayerInfoProto.PlayerInfosOrBuilder>(
                  (org.whk.protobuf.message.PlayerInfoProto.PlayerInfos) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 14;
        onChanged();
        return playerInfosBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.CreatePlayerProto.CreatePlayer, org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.Builder, org.whk.protobuf.message.CreatePlayerProto.CreatePlayerOrBuilder> createPlayerBuilder_;
      /**
       * <code>.CreatePlayer createPlayer = 15;</code>
       * @return Whether the createPlayer field is set.
       */
      @java.lang.Override
      public boolean hasCreatePlayer() {
        return bodyCase_ == 15;
      }
      /**
       * <code>.CreatePlayer createPlayer = 15;</code>
       * @return The createPlayer.
       */
      @java.lang.Override
      public org.whk.protobuf.message.CreatePlayerProto.CreatePlayer getCreatePlayer() {
        if (createPlayerBuilder_ == null) {
          if (bodyCase_ == 15) {
            return (org.whk.protobuf.message.CreatePlayerProto.CreatePlayer) body_;
          }
          return org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.getDefaultInstance();
        } else {
          if (bodyCase_ == 15) {
            return createPlayerBuilder_.getMessage();
          }
          return org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.getDefaultInstance();
        }
      }
      /**
       * <code>.CreatePlayer createPlayer = 15;</code>
       */
      public Builder setCreatePlayer(org.whk.protobuf.message.CreatePlayerProto.CreatePlayer value) {
        if (createPlayerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          createPlayerBuilder_.setMessage(value);
        }
        bodyCase_ = 15;
        return this;
      }
      /**
       * <code>.CreatePlayer createPlayer = 15;</code>
       */
      public Builder setCreatePlayer(
          org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.Builder builderForValue) {
        if (createPlayerBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          createPlayerBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 15;
        return this;
      }
      /**
       * <code>.CreatePlayer createPlayer = 15;</code>
       */
      public Builder mergeCreatePlayer(org.whk.protobuf.message.CreatePlayerProto.CreatePlayer value) {
        if (createPlayerBuilder_ == null) {
          if (bodyCase_ == 15 &&
              body_ != org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.getDefaultInstance()) {
            body_ = org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.newBuilder((org.whk.protobuf.message.CreatePlayerProto.CreatePlayer) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 15) {
            createPlayerBuilder_.mergeFrom(value);
          } else {
            createPlayerBuilder_.setMessage(value);
          }
        }
        bodyCase_ = 15;
        return this;
      }
      /**
       * <code>.CreatePlayer createPlayer = 15;</code>
       */
      public Builder clearCreatePlayer() {
        if (createPlayerBuilder_ == null) {
          if (bodyCase_ == 15) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 15) {
            bodyCase_ = 0;
            body_ = null;
          }
          createPlayerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.CreatePlayer createPlayer = 15;</code>
       */
      public org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.Builder getCreatePlayerBuilder() {
        return getCreatePlayerFieldBuilder().getBuilder();
      }
      /**
       * <code>.CreatePlayer createPlayer = 15;</code>
       */
      @java.lang.Override
      public org.whk.protobuf.message.CreatePlayerProto.CreatePlayerOrBuilder getCreatePlayerOrBuilder() {
        if ((bodyCase_ == 15) && (createPlayerBuilder_ != null)) {
          return createPlayerBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 15) {
            return (org.whk.protobuf.message.CreatePlayerProto.CreatePlayer) body_;
          }
          return org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.getDefaultInstance();
        }
      }
      /**
       * <code>.CreatePlayer createPlayer = 15;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.CreatePlayerProto.CreatePlayer, org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.Builder, org.whk.protobuf.message.CreatePlayerProto.CreatePlayerOrBuilder> 
          getCreatePlayerFieldBuilder() {
        if (createPlayerBuilder_ == null) {
          if (!(bodyCase_ == 15)) {
            body_ = org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.getDefaultInstance();
          }
          createPlayerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.whk.protobuf.message.CreatePlayerProto.CreatePlayer, org.whk.protobuf.message.CreatePlayerProto.CreatePlayer.Builder, org.whk.protobuf.message.CreatePlayerProto.CreatePlayerOrBuilder>(
                  (org.whk.protobuf.message.CreatePlayerProto.CreatePlayer) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 15;
        onChanged();
        return createPlayerBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final org.whk.protobuf.message.MessageProto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.whk.protobuf.message.MessageProto.Message();
    }

    public static org.whk.protobuf.message.MessageProto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.whk.protobuf.message.MessageProto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\032\013Login.proto\032\013Empty.prot" +
      "o\032\nTips.proto\032\020PlayerInfo.proto\032\022CreateP" +
      "layer.proto\"\334\001\n\007Message\022\017\n\007command\030\001 \001(\005" +
      "\022\035\n\010loginRes\030\n \001(\0132\t.LoginResH\000\022\035\n\010login" +
      "Req\030\013 \001(\0132\t.LoginReqH\000\022\027\n\005empty\030\014 \001(\0132\006." +
      "EmptyH\000\022\025\n\004tips\030\r \001(\0132\005.TipsH\000\022#\n\013player" +
      "Infos\030\016 \001(\0132\014.PlayerInfosH\000\022%\n\014createPla" +
      "yer\030\017 \001(\0132\r.CreatePlayerH\000B\006\n\004bodyB(\n\030or" +
      "g.whk.protobuf.messageB\014MessageProtob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.whk.protobuf.message.LoginProto.getDescriptor(),
          org.whk.protobuf.message.EmptyProto.getDescriptor(),
          org.whk.protobuf.message.TipsProto.getDescriptor(),
          org.whk.protobuf.message.PlayerInfoProto.getDescriptor(),
          org.whk.protobuf.message.CreatePlayerProto.getDescriptor(),
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Command", "LoginRes", "LoginReq", "Empty", "Tips", "PlayerInfos", "CreatePlayer", "Body", });
    descriptor.resolveAllFeaturesImmutable();
    org.whk.protobuf.message.LoginProto.getDescriptor();
    org.whk.protobuf.message.EmptyProto.getDescriptor();
    org.whk.protobuf.message.TipsProto.getDescriptor();
    org.whk.protobuf.message.PlayerInfoProto.getDescriptor();
    org.whk.protobuf.message.CreatePlayerProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
