// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MessageWrapper.proto
// Protobuf Java Version: 4.27.1

package org.whk.protobuf.message;

public final class MessageWrapperProto {
  private MessageWrapperProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      MessageWrapperProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 playerId = 1;</code>
     * @return The playerId.
     */
    long getPlayerId();

    /**
     * <code>.Message message = 2;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>.Message message = 2;</code>
     * @return The message.
     */
    org.whk.protobuf.message.MessageProto.Message getMessage();
    /**
     * <code>.Message message = 2;</code>
     */
    org.whk.protobuf.message.MessageProto.MessageOrBuilder getMessageOrBuilder();
  }
  /**
   * Protobuf type {@code MessageWrapper}
   */
  public static final class MessageWrapper extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MessageWrapper)
      MessageWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        MessageWrapper.class.getName());
    }
    // Use MessageWrapper.newBuilder() to construct.
    private MessageWrapper(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MessageWrapper() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.whk.protobuf.message.MessageWrapperProto.internal_static_MessageWrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.whk.protobuf.message.MessageWrapperProto.internal_static_MessageWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.whk.protobuf.message.MessageWrapperProto.MessageWrapper.class, org.whk.protobuf.message.MessageWrapperProto.MessageWrapper.Builder.class);
    }

    private int bitField0_;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_ = 0L;
    /**
     * <code>int64 playerId = 1;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public long getPlayerId() {
      return playerId_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private org.whk.protobuf.message.MessageProto.Message message_;
    /**
     * <code>.Message message = 2;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Message message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public org.whk.protobuf.message.MessageProto.Message getMessage() {
      return message_ == null ? org.whk.protobuf.message.MessageProto.Message.getDefaultInstance() : message_;
    }
    /**
     * <code>.Message message = 2;</code>
     */
    @java.lang.Override
    public org.whk.protobuf.message.MessageProto.MessageOrBuilder getMessageOrBuilder() {
      return message_ == null ? org.whk.protobuf.message.MessageProto.Message.getDefaultInstance() : message_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0L) {
        output.writeInt64(1, playerId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getMessage());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMessage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.whk.protobuf.message.MessageWrapperProto.MessageWrapper)) {
        return super.equals(obj);
      }
      org.whk.protobuf.message.MessageWrapperProto.MessageWrapper other = (org.whk.protobuf.message.MessageWrapperProto.MessageWrapper) obj;

      if (getPlayerId()
          != other.getPlayerId()) return false;
      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPlayerId());
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.whk.protobuf.message.MessageWrapperProto.MessageWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageWrapper)
        org.whk.protobuf.message.MessageWrapperProto.MessageWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.whk.protobuf.message.MessageWrapperProto.internal_static_MessageWrapper_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.whk.protobuf.message.MessageWrapperProto.internal_static_MessageWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.whk.protobuf.message.MessageWrapperProto.MessageWrapper.class, org.whk.protobuf.message.MessageWrapperProto.MessageWrapper.Builder.class);
      }

      // Construct using org.whk.protobuf.message.MessageWrapperProto.MessageWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        playerId_ = 0L;
        message_ = null;
        if (messageBuilder_ != null) {
          messageBuilder_.dispose();
          messageBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.whk.protobuf.message.MessageWrapperProto.internal_static_MessageWrapper_descriptor;
      }

      @java.lang.Override
      public org.whk.protobuf.message.MessageWrapperProto.MessageWrapper getDefaultInstanceForType() {
        return org.whk.protobuf.message.MessageWrapperProto.MessageWrapper.getDefaultInstance();
      }

      @java.lang.Override
      public org.whk.protobuf.message.MessageWrapperProto.MessageWrapper build() {
        org.whk.protobuf.message.MessageWrapperProto.MessageWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.whk.protobuf.message.MessageWrapperProto.MessageWrapper buildPartial() {
        org.whk.protobuf.message.MessageWrapperProto.MessageWrapper result = new org.whk.protobuf.message.MessageWrapperProto.MessageWrapper(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.whk.protobuf.message.MessageWrapperProto.MessageWrapper result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.playerId_ = playerId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.message_ = messageBuilder_ == null
              ? message_
              : messageBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.whk.protobuf.message.MessageWrapperProto.MessageWrapper) {
          return mergeFrom((org.whk.protobuf.message.MessageWrapperProto.MessageWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.whk.protobuf.message.MessageWrapperProto.MessageWrapper other) {
        if (other == org.whk.protobuf.message.MessageWrapperProto.MessageWrapper.getDefaultInstance()) return this;
        if (other.getPlayerId() != 0L) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                playerId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getMessageFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long playerId_ ;
      /**
       * <code>int64 playerId = 1;</code>
       * @return The playerId.
       */
      @java.lang.Override
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>int64 playerId = 1;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(long value) {

        playerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 playerId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private org.whk.protobuf.message.MessageProto.Message message_;
      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.MessageProto.Message, org.whk.protobuf.message.MessageProto.Message.Builder, org.whk.protobuf.message.MessageProto.MessageOrBuilder> messageBuilder_;
      /**
       * <code>.Message message = 2;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.Message message = 2;</code>
       * @return The message.
       */
      public org.whk.protobuf.message.MessageProto.Message getMessage() {
        if (messageBuilder_ == null) {
          return message_ == null ? org.whk.protobuf.message.MessageProto.Message.getDefaultInstance() : message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      /**
       * <code>.Message message = 2;</code>
       */
      public Builder setMessage(org.whk.protobuf.message.MessageProto.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
        } else {
          messageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.Message message = 2;</code>
       */
      public Builder setMessage(
          org.whk.protobuf.message.MessageProto.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.Message message = 2;</code>
       */
      public Builder mergeMessage(org.whk.protobuf.message.MessageProto.Message value) {
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            message_ != null &&
            message_ != org.whk.protobuf.message.MessageProto.Message.getDefaultInstance()) {
            getMessageBuilder().mergeFrom(value);
          } else {
            message_ = value;
          }
        } else {
          messageBuilder_.mergeFrom(value);
        }
        if (message_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.Message message = 2;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = null;
        if (messageBuilder_ != null) {
          messageBuilder_.dispose();
          messageBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.Message message = 2;</code>
       */
      public org.whk.protobuf.message.MessageProto.Message.Builder getMessageBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.Message message = 2;</code>
       */
      public org.whk.protobuf.message.MessageProto.MessageOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_ == null ?
              org.whk.protobuf.message.MessageProto.Message.getDefaultInstance() : message_;
        }
      }
      /**
       * <code>.Message message = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.whk.protobuf.message.MessageProto.Message, org.whk.protobuf.message.MessageProto.Message.Builder, org.whk.protobuf.message.MessageProto.MessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.whk.protobuf.message.MessageProto.Message, org.whk.protobuf.message.MessageProto.Message.Builder, org.whk.protobuf.message.MessageProto.MessageOrBuilder>(
                  getMessage(),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:MessageWrapper)
    }

    // @@protoc_insertion_point(class_scope:MessageWrapper)
    private static final org.whk.protobuf.message.MessageWrapperProto.MessageWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.whk.protobuf.message.MessageWrapperProto.MessageWrapper();
    }

    public static org.whk.protobuf.message.MessageWrapperProto.MessageWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageWrapper>
        PARSER = new com.google.protobuf.AbstractParser<MessageWrapper>() {
      @java.lang.Override
      public MessageWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageWrapper> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.whk.protobuf.message.MessageWrapperProto.MessageWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024MessageWrapper.proto\032\rMessage.proto\"=\n" +
      "\016MessageWrapper\022\020\n\010playerId\030\001 \001(\003\022\031\n\007mes" +
      "sage\030\002 \001(\0132\010.MessageB/\n\030org.whk.protobuf" +
      ".messageB\023MessageWrapperProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.whk.protobuf.message.MessageProto.getDescriptor(),
        });
    internal_static_MessageWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MessageWrapper_descriptor,
        new java.lang.String[] { "PlayerId", "Message", });
    descriptor.resolveAllFeaturesImmutable();
    org.whk.protobuf.message.MessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
