

spring:
  application:
    name: game-server

  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
          replication-factor: 1
  kafka:
    producer:
      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer


# 服务注册与发现
eureka:
  client:
    register-with-eureka: true #被其它服务调用时需向Eureka注册
    fetch-registry: true #被其它服务调用时需向Eureka注册
    service-url:
      defaultZone: "http://127.0.0.1:5010/eureka"  #客户端与服务端交互地址，多个逗号隔开

  instance:
    prefer-ip-address: true #将自己的ip注册到Eureka服务中
    instance-id: ${spring.application.name} #实例id
    metadata-map:
      id: 1

game:
  kafka-topic:
    group-id: 1
    server: 1
