server:
  port: 5019

spring:
  application:
    name: web-center

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          auto: update

  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/admin?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT
          username: root
          password: Sogoun@2023
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://localhost:3306/admin?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT
          username: root
          password: Sogoun@2023
          driver-class-name: com.mysql.cj.jdbc.Driver

  web:
    resources:
      static-locations: classpath:/static/

# 服务注册与发现
eureka:
  client:
    register-with-eureka: true #被其它服务调用时需向Eureka注册
    fetch-registry: true #被其它服务调用时需向Eureka注册
    service-url:
      defaultZone: "http://127.0.0.1:5010/eureka"  #客户端与服务端交互地址，多个逗号隔开

  instance:
    prefer-ip-address: true #将自己的ip注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #实例id

game:
  xml_path: config/zh_CN/