# 网址 "http://127.0.0.1:5010/"
server:
  port: 5010

spring:
  application:
    name: eureka-server

# 服务注册与发现
eureka:
  instance:
    hostname: 127.0.0.1

  client:
    register-with-eureka: false #向Eureka注册自己
    fetch-registry: false #检索服务项
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/

  server:
    enable-self-preservation: false #自保护设置
    eviction-interval-timer-in-ms: 60000 #清理失效结点的间隔