# 网址 "http://localhost:5010/"
server:
  port: 5010

spring:
  application:
    name: eureka-server

# 服务注册与发现
eureka:
  instance:
    hostname: 127.0.0.1

  client:
    registerWithEureka: false #被其它服务调用时需向Eureka注册
    fetchRegistry: false #被其它服务调用时需向Eureka注册

  server:
    enable-self-preservation: false #自保护设置
    eviction-interval-timer-in-ms: 60000 #清理失效结点的间隔