// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: CreatePlayer.proto
// Protobuf Java Version: 4.27.1

package com.whk.protobuf.message;

public final class CreatePlayerProto {
  private CreatePlayerProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      CreatePlayerProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreatePlayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CreatePlayer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>int32 serverId = 2;</code>
     * @return The serverId.
     */
    int getServerId();

    /**
     * <code>int32 sex = 3;</code>
     * @return The sex.
     */
    int getSex();

    /**
     * <code>int32 kind = 4;</code>
     * @return The kind.
     */
    int getKind();
  }
  /**
   * Protobuf type {@code CreatePlayer}
   */
  public static final class CreatePlayer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CreatePlayer)
      CreatePlayerOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        CreatePlayer.class.getName());
    }
    // Use CreatePlayer.newBuilder() to construct.
    private CreatePlayer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CreatePlayer() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whk.protobuf.message.CreatePlayerProto.internal_static_CreatePlayer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whk.protobuf.message.CreatePlayerProto.internal_static_CreatePlayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whk.protobuf.message.CreatePlayerProto.CreatePlayer.class, com.whk.protobuf.message.CreatePlayerProto.CreatePlayer.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_ = 0L;
    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int SERVERID_FIELD_NUMBER = 2;
    private int serverId_ = 0;
    /**
     * <code>int32 serverId = 2;</code>
     * @return The serverId.
     */
    @java.lang.Override
    public int getServerId() {
      return serverId_;
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_ = 0;
    /**
     * <code>int32 sex = 3;</code>
     * @return The sex.
     */
    @java.lang.Override
    public int getSex() {
      return sex_;
    }

    public static final int KIND_FIELD_NUMBER = 4;
    private int kind_ = 0;
    /**
     * <code>int32 kind = 4;</code>
     * @return The kind.
     */
    @java.lang.Override
    public int getKind() {
      return kind_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (serverId_ != 0) {
        output.writeInt32(2, serverId_);
      }
      if (sex_ != 0) {
        output.writeInt32(3, sex_);
      }
      if (kind_ != 0) {
        output.writeInt32(4, kind_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (serverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverId_);
      }
      if (sex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sex_);
      }
      if (kind_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, kind_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.whk.protobuf.message.CreatePlayerProto.CreatePlayer)) {
        return super.equals(obj);
      }
      com.whk.protobuf.message.CreatePlayerProto.CreatePlayer other = (com.whk.protobuf.message.CreatePlayerProto.CreatePlayer) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (getServerId()
          != other.getServerId()) return false;
      if (getSex()
          != other.getSex()) return false;
      if (getKind()
          != other.getKind()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + getSex();
      hash = (37 * hash) + KIND_FIELD_NUMBER;
      hash = (53 * hash) + getKind();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.whk.protobuf.message.CreatePlayerProto.CreatePlayer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CreatePlayer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CreatePlayer)
        com.whk.protobuf.message.CreatePlayerProto.CreatePlayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whk.protobuf.message.CreatePlayerProto.internal_static_CreatePlayer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whk.protobuf.message.CreatePlayerProto.internal_static_CreatePlayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whk.protobuf.message.CreatePlayerProto.CreatePlayer.class, com.whk.protobuf.message.CreatePlayerProto.CreatePlayer.Builder.class);
      }

      // Construct using com.whk.protobuf.message.CreatePlayerProto.CreatePlayer.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = 0L;
        serverId_ = 0;
        sex_ = 0;
        kind_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whk.protobuf.message.CreatePlayerProto.internal_static_CreatePlayer_descriptor;
      }

      @java.lang.Override
      public com.whk.protobuf.message.CreatePlayerProto.CreatePlayer getDefaultInstanceForType() {
        return com.whk.protobuf.message.CreatePlayerProto.CreatePlayer.getDefaultInstance();
      }

      @java.lang.Override
      public com.whk.protobuf.message.CreatePlayerProto.CreatePlayer build() {
        com.whk.protobuf.message.CreatePlayerProto.CreatePlayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.whk.protobuf.message.CreatePlayerProto.CreatePlayer buildPartial() {
        com.whk.protobuf.message.CreatePlayerProto.CreatePlayer result = new com.whk.protobuf.message.CreatePlayerProto.CreatePlayer(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.whk.protobuf.message.CreatePlayerProto.CreatePlayer result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.serverId_ = serverId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sex_ = sex_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.kind_ = kind_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whk.protobuf.message.CreatePlayerProto.CreatePlayer) {
          return mergeFrom((com.whk.protobuf.message.CreatePlayerProto.CreatePlayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whk.protobuf.message.CreatePlayerProto.CreatePlayer other) {
        if (other == com.whk.protobuf.message.CreatePlayerProto.CreatePlayer.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getServerId() != 0) {
          setServerId(other.getServerId());
        }
        if (other.getSex() != 0) {
          setSex(other.getSex());
        }
        if (other.getKind() != 0) {
          setKind(other.getKind());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                serverId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                sex_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                kind_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <code>int64 userId = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private int serverId_ ;
      /**
       * <code>int32 serverId = 2;</code>
       * @return The serverId.
       */
      @java.lang.Override
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>int32 serverId = 2;</code>
       * @param value The serverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerId(int value) {

        serverId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serverId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverId_ = 0;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <code>int32 sex = 3;</code>
       * @return The sex.
       */
      @java.lang.Override
      public int getSex() {
        return sex_;
      }
      /**
       * <code>int32 sex = 3;</code>
       * @param value The sex to set.
       * @return This builder for chaining.
       */
      public Builder setSex(int value) {

        sex_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 0;
        onChanged();
        return this;
      }

      private int kind_ ;
      /**
       * <code>int32 kind = 4;</code>
       * @return The kind.
       */
      @java.lang.Override
      public int getKind() {
        return kind_;
      }
      /**
       * <code>int32 kind = 4;</code>
       * @param value The kind to set.
       * @return This builder for chaining.
       */
      public Builder setKind(int value) {

        kind_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 kind = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKind() {
        bitField0_ = (bitField0_ & ~0x00000008);
        kind_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CreatePlayer)
    }

    // @@protoc_insertion_point(class_scope:CreatePlayer)
    private static final com.whk.protobuf.message.CreatePlayerProto.CreatePlayer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.whk.protobuf.message.CreatePlayerProto.CreatePlayer();
    }

    public static com.whk.protobuf.message.CreatePlayerProto.CreatePlayer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreatePlayer>
        PARSER = new com.google.protobuf.AbstractParser<CreatePlayer>() {
      @java.lang.Override
      public CreatePlayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CreatePlayer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreatePlayer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.whk.protobuf.message.CreatePlayerProto.CreatePlayer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreatePlayer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CreatePlayer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022CreatePlayer.proto\"K\n\014CreatePlayer\022\016\n\006" +
      "userId\030\001 \001(\003\022\020\n\010serverId\030\002 \001(\005\022\013\n\003sex\030\003 " +
      "\001(\005\022\014\n\004kind\030\004 \001(\005B-\n\030com.whk.protobuf.me" +
      "ssageB\021CreatePlayerProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreatePlayer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreatePlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CreatePlayer_descriptor,
        new java.lang.String[] { "UserId", "ServerId", "Sex", "Kind", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
