// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MSGID.proto
// Protobuf Java Version: 4.30.0

package com.whk.protobuf.message;

public final class MSGIDProto {
  private MSGIDProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 0,
      /* suffix= */ "",
      MSGIDProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MSGID}
   */
  public enum MSGID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * gate server
     * </pre>
     *
     * <code>gate_server = 0;</code>
     */
    gate_server(0),
    /**
     * <code>LoginProto_ReqLogin = 10;</code>
     */
    LoginProto_ReqLogin(10),
    /**
     * <code>CreatePlayerProto_CreatePlayer = 11;</code>
     */
    CreatePlayerProto_CreatePlayer(11),
    /**
     * <code>PlayerInfoProto_ReqPlayerLogin = 12;</code>
     */
    PlayerInfoProto_ReqPlayerLogin(12),
    /**
     * <code>PlayerInfoProto_TestMessage = 13;</code>
     */
    PlayerInfoProto_TestMessage(13),
    /**
     * <code>PlayerInfoProto_ReqPlayers = 14;</code>
     */
    PlayerInfoProto_ReqPlayers(14),
    /**
     * <code>SceneProto_ReqEnterScene = 15;</code>
     */
    SceneProto_ReqEnterScene(15),
    /**
     * <code>PlayerInfoProto_PlayerInfos = 16;</code>
     */
    PlayerInfoProto_PlayerInfos(16),
    /**
     * <code>TipsProto_Tips = 17;</code>
     */
    TipsProto_Tips(17),
    /**
     * <code>LoginProto_ResLogin = 18;</code>
     */
    LoginProto_ResLogin(18),
    /**
     * <code>SceneProto_ResEnterScene = 19;</code>
     */
    SceneProto_ResEnterScene(19),
    /**
     * <code>CreatePlayerProto_ResCreatePlayer = 20;</code>
     */
    CreatePlayerProto_ResCreatePlayer(20),
    /**
     * <pre>
     * game server
     * </pre>
     *
     * <code>game_server = 1;</code>
     */
    game_server(1),
    /**
     * <code>PlayerInfoProto_ReqLevelUp = 100;</code>
     */
    PlayerInfoProto_ReqLevelUp(100),
    /**
     * <code>PlayerInfoProto_ResLevelUp = 101;</code>
     */
    PlayerInfoProto_ResLevelUp(101),
    /**
     * <pre>
     * scene server
     * </pre>
     *
     * <code>scene_server = 2;</code>
     */
    scene_server(2),
    /**
     * <code>SkillProto_ReqReleaseSkill = 102;</code>
     */
    SkillProto_ReqReleaseSkill(102),
    /**
     * <code>SceneProto_SceneMessage = 103;</code>
     */
    SceneProto_SceneMessage(103),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 0,
        /* suffix= */ "",
        MSGID.class.getName());
    }
    /**
     * <pre>
     * gate server
     * </pre>
     *
     * <code>gate_server = 0;</code>
     */
    public static final int gate_server_VALUE = 0;
    /**
     * <code>LoginProto_ReqLogin = 10;</code>
     */
    public static final int LoginProto_ReqLogin_VALUE = 10;
    /**
     * <code>CreatePlayerProto_CreatePlayer = 11;</code>
     */
    public static final int CreatePlayerProto_CreatePlayer_VALUE = 11;
    /**
     * <code>PlayerInfoProto_ReqPlayerLogin = 12;</code>
     */
    public static final int PlayerInfoProto_ReqPlayerLogin_VALUE = 12;
    /**
     * <code>PlayerInfoProto_TestMessage = 13;</code>
     */
    public static final int PlayerInfoProto_TestMessage_VALUE = 13;
    /**
     * <code>PlayerInfoProto_ReqPlayers = 14;</code>
     */
    public static final int PlayerInfoProto_ReqPlayers_VALUE = 14;
    /**
     * <code>SceneProto_ReqEnterScene = 15;</code>
     */
    public static final int SceneProto_ReqEnterScene_VALUE = 15;
    /**
     * <code>PlayerInfoProto_PlayerInfos = 16;</code>
     */
    public static final int PlayerInfoProto_PlayerInfos_VALUE = 16;
    /**
     * <code>TipsProto_Tips = 17;</code>
     */
    public static final int TipsProto_Tips_VALUE = 17;
    /**
     * <code>LoginProto_ResLogin = 18;</code>
     */
    public static final int LoginProto_ResLogin_VALUE = 18;
    /**
     * <code>SceneProto_ResEnterScene = 19;</code>
     */
    public static final int SceneProto_ResEnterScene_VALUE = 19;
    /**
     * <code>CreatePlayerProto_ResCreatePlayer = 20;</code>
     */
    public static final int CreatePlayerProto_ResCreatePlayer_VALUE = 20;
    /**
     * <pre>
     * game server
     * </pre>
     *
     * <code>game_server = 1;</code>
     */
    public static final int game_server_VALUE = 1;
    /**
     * <code>PlayerInfoProto_ReqLevelUp = 100;</code>
     */
    public static final int PlayerInfoProto_ReqLevelUp_VALUE = 100;
    /**
     * <code>PlayerInfoProto_ResLevelUp = 101;</code>
     */
    public static final int PlayerInfoProto_ResLevelUp_VALUE = 101;
    /**
     * <pre>
     * scene server
     * </pre>
     *
     * <code>scene_server = 2;</code>
     */
    public static final int scene_server_VALUE = 2;
    /**
     * <code>SkillProto_ReqReleaseSkill = 102;</code>
     */
    public static final int SkillProto_ReqReleaseSkill_VALUE = 102;
    /**
     * <code>SceneProto_SceneMessage = 103;</code>
     */
    public static final int SceneProto_SceneMessage_VALUE = 103;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MSGID valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MSGID forNumber(int value) {
      switch (value) {
        case 0: return gate_server;
        case 10: return LoginProto_ReqLogin;
        case 11: return CreatePlayerProto_CreatePlayer;
        case 12: return PlayerInfoProto_ReqPlayerLogin;
        case 13: return PlayerInfoProto_TestMessage;
        case 14: return PlayerInfoProto_ReqPlayers;
        case 15: return SceneProto_ReqEnterScene;
        case 16: return PlayerInfoProto_PlayerInfos;
        case 17: return TipsProto_Tips;
        case 18: return LoginProto_ResLogin;
        case 19: return SceneProto_ResEnterScene;
        case 20: return CreatePlayerProto_ResCreatePlayer;
        case 1: return game_server;
        case 100: return PlayerInfoProto_ReqLevelUp;
        case 101: return PlayerInfoProto_ResLevelUp;
        case 2: return scene_server;
        case 102: return SkillProto_ReqReleaseSkill;
        case 103: return SceneProto_SceneMessage;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MSGID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MSGID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MSGID>() {
            public MSGID findValueByNumber(int number) {
              return MSGID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.whk.protobuf.message.MSGIDProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MSGID[] VALUES = values();

    public static MSGID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MSGID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MSGID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013MSGID.proto*\213\004\n\005MSGID\022\017\n\013gate_server\020\000" +
      "\022\027\n\023LoginProto_ReqLogin\020\n\022\"\n\036CreatePlaye" +
      "rProto_CreatePlayer\020\013\022\"\n\036PlayerInfoProto" +
      "_ReqPlayerLogin\020\014\022\037\n\033PlayerInfoProto_Tes" +
      "tMessage\020\r\022\036\n\032PlayerInfoProto_ReqPlayers" +
      "\020\016\022\034\n\030SceneProto_ReqEnterScene\020\017\022\037\n\033Play" +
      "erInfoProto_PlayerInfos\020\020\022\022\n\016TipsProto_T" +
      "ips\020\021\022\027\n\023LoginProto_ResLogin\020\022\022\034\n\030SceneP" +
      "roto_ResEnterScene\020\023\022%\n!CreatePlayerProt" +
      "o_ResCreatePlayer\020\024\022\017\n\013game_server\020\001\022\036\n\032" +
      "PlayerInfoProto_ReqLevelUp\020d\022\036\n\032PlayerIn" +
      "foProto_ResLevelUp\020e\022\020\n\014scene_server\020\002\022\036" +
      "\n\032SkillProto_ReqReleaseSkill\020f\022\033\n\027SceneP" +
      "roto_SceneMessage\020gB&\n\030com.whk.protobuf." +
      "messageB\nMSGIDProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
