// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Skill.proto
// Protobuf Java Version: 4.27.1

package com.whk.protobuf.message;

public final class SkillProto {
  private SkillProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      SkillProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MovementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Movement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 x = 1;</code>
     * @return The x.
     */
    int getX();

    /**
     * <code>int32 y = 2;</code>
     * @return The y.
     */
    int getY();

    /**
     * <code>int32 z = 3;</code>
     * @return The z.
     */
    int getZ();
  }
  /**
   * Protobuf type {@code Movement}
   */
  public static final class Movement extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Movement)
      MovementOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        Movement.class.getName());
    }
    // Use Movement.newBuilder() to construct.
    private Movement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Movement() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whk.protobuf.message.SkillProto.internal_static_Movement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whk.protobuf.message.SkillProto.internal_static_Movement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whk.protobuf.message.SkillProto.Movement.class, com.whk.protobuf.message.SkillProto.Movement.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_ = 0;
    /**
     * <code>int32 x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_ = 0;
    /**
     * <code>int32 y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private int z_ = 0;
    /**
     * <code>int32 z = 3;</code>
     * @return The z.
     */
    @java.lang.Override
    public int getZ() {
      return z_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
      if (z_ != 0) {
        output.writeInt32(3, z_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      if (z_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.whk.protobuf.message.SkillProto.Movement)) {
        return super.equals(obj);
      }
      com.whk.protobuf.message.SkillProto.Movement other = (com.whk.protobuf.message.SkillProto.Movement) obj;

      if (getX()
          != other.getX()) return false;
      if (getY()
          != other.getY()) return false;
      if (getZ()
          != other.getZ()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + getZ();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.whk.protobuf.message.SkillProto.Movement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.SkillProto.Movement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.Movement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.SkillProto.Movement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.Movement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.SkillProto.Movement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.Movement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.whk.protobuf.message.SkillProto.Movement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.whk.protobuf.message.SkillProto.Movement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.whk.protobuf.message.SkillProto.Movement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.Movement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.whk.protobuf.message.SkillProto.Movement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.whk.protobuf.message.SkillProto.Movement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Movement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Movement)
        com.whk.protobuf.message.SkillProto.MovementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whk.protobuf.message.SkillProto.internal_static_Movement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whk.protobuf.message.SkillProto.internal_static_Movement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whk.protobuf.message.SkillProto.Movement.class, com.whk.protobuf.message.SkillProto.Movement.Builder.class);
      }

      // Construct using com.whk.protobuf.message.SkillProto.Movement.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x_ = 0;
        y_ = 0;
        z_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whk.protobuf.message.SkillProto.internal_static_Movement_descriptor;
      }

      @java.lang.Override
      public com.whk.protobuf.message.SkillProto.Movement getDefaultInstanceForType() {
        return com.whk.protobuf.message.SkillProto.Movement.getDefaultInstance();
      }

      @java.lang.Override
      public com.whk.protobuf.message.SkillProto.Movement build() {
        com.whk.protobuf.message.SkillProto.Movement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.whk.protobuf.message.SkillProto.Movement buildPartial() {
        com.whk.protobuf.message.SkillProto.Movement result = new com.whk.protobuf.message.SkillProto.Movement(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.whk.protobuf.message.SkillProto.Movement result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.z_ = z_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whk.protobuf.message.SkillProto.Movement) {
          return mergeFrom((com.whk.protobuf.message.SkillProto.Movement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whk.protobuf.message.SkillProto.Movement other) {
        if (other == com.whk.protobuf.message.SkillProto.Movement.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        if (other.getZ() != 0) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                x_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                y_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                z_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int x_ ;
      /**
       * <code>int32 x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public int getX() {
        return x_;
      }
      /**
       * <code>int32 x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(int value) {

        x_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>int32 y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public int getY() {
        return y_;
      }
      /**
       * <code>int32 y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(int value) {

        y_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      private int z_ ;
      /**
       * <code>int32 z = 3;</code>
       * @return The z.
       */
      @java.lang.Override
      public int getZ() {
        return z_;
      }
      /**
       * <code>int32 z = 3;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(int value) {

        z_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 z = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Movement)
    }

    // @@protoc_insertion_point(class_scope:Movement)
    private static final com.whk.protobuf.message.SkillProto.Movement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.whk.protobuf.message.SkillProto.Movement();
    }

    public static com.whk.protobuf.message.SkillProto.Movement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Movement>
        PARSER = new com.google.protobuf.AbstractParser<Movement>() {
      @java.lang.Override
      public Movement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Movement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Movement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.whk.protobuf.message.SkillProto.Movement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReqReleaseSkillOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqReleaseSkill)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 skillId = 1;</code>
     * @return The skillId.
     */
    int getSkillId();
  }
  /**
   * Protobuf type {@code ReqReleaseSkill}
   */
  public static final class ReqReleaseSkill extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReqReleaseSkill)
      ReqReleaseSkillOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        ReqReleaseSkill.class.getName());
    }
    // Use ReqReleaseSkill.newBuilder() to construct.
    private ReqReleaseSkill(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ReqReleaseSkill() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whk.protobuf.message.SkillProto.internal_static_ReqReleaseSkill_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whk.protobuf.message.SkillProto.internal_static_ReqReleaseSkill_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whk.protobuf.message.SkillProto.ReqReleaseSkill.class, com.whk.protobuf.message.SkillProto.ReqReleaseSkill.Builder.class);
    }

    public static final int SKILLID_FIELD_NUMBER = 1;
    private int skillId_ = 0;
    /**
     * <code>int32 skillId = 1;</code>
     * @return The skillId.
     */
    @java.lang.Override
    public int getSkillId() {
      return skillId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (skillId_ != 0) {
        output.writeInt32(1, skillId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (skillId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, skillId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.whk.protobuf.message.SkillProto.ReqReleaseSkill)) {
        return super.equals(obj);
      }
      com.whk.protobuf.message.SkillProto.ReqReleaseSkill other = (com.whk.protobuf.message.SkillProto.ReqReleaseSkill) obj;

      if (getSkillId()
          != other.getSkillId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SKILLID_FIELD_NUMBER;
      hash = (53 * hash) + getSkillId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.whk.protobuf.message.SkillProto.ReqReleaseSkill prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReqReleaseSkill}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqReleaseSkill)
        com.whk.protobuf.message.SkillProto.ReqReleaseSkillOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whk.protobuf.message.SkillProto.internal_static_ReqReleaseSkill_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whk.protobuf.message.SkillProto.internal_static_ReqReleaseSkill_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whk.protobuf.message.SkillProto.ReqReleaseSkill.class, com.whk.protobuf.message.SkillProto.ReqReleaseSkill.Builder.class);
      }

      // Construct using com.whk.protobuf.message.SkillProto.ReqReleaseSkill.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        skillId_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whk.protobuf.message.SkillProto.internal_static_ReqReleaseSkill_descriptor;
      }

      @java.lang.Override
      public com.whk.protobuf.message.SkillProto.ReqReleaseSkill getDefaultInstanceForType() {
        return com.whk.protobuf.message.SkillProto.ReqReleaseSkill.getDefaultInstance();
      }

      @java.lang.Override
      public com.whk.protobuf.message.SkillProto.ReqReleaseSkill build() {
        com.whk.protobuf.message.SkillProto.ReqReleaseSkill result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.whk.protobuf.message.SkillProto.ReqReleaseSkill buildPartial() {
        com.whk.protobuf.message.SkillProto.ReqReleaseSkill result = new com.whk.protobuf.message.SkillProto.ReqReleaseSkill(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.whk.protobuf.message.SkillProto.ReqReleaseSkill result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.skillId_ = skillId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whk.protobuf.message.SkillProto.ReqReleaseSkill) {
          return mergeFrom((com.whk.protobuf.message.SkillProto.ReqReleaseSkill)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whk.protobuf.message.SkillProto.ReqReleaseSkill other) {
        if (other == com.whk.protobuf.message.SkillProto.ReqReleaseSkill.getDefaultInstance()) return this;
        if (other.getSkillId() != 0) {
          setSkillId(other.getSkillId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                skillId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int skillId_ ;
      /**
       * <code>int32 skillId = 1;</code>
       * @return The skillId.
       */
      @java.lang.Override
      public int getSkillId() {
        return skillId_;
      }
      /**
       * <code>int32 skillId = 1;</code>
       * @param value The skillId to set.
       * @return This builder for chaining.
       */
      public Builder setSkillId(int value) {

        skillId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 skillId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkillId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        skillId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReqReleaseSkill)
    }

    // @@protoc_insertion_point(class_scope:ReqReleaseSkill)
    private static final com.whk.protobuf.message.SkillProto.ReqReleaseSkill DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.whk.protobuf.message.SkillProto.ReqReleaseSkill();
    }

    public static com.whk.protobuf.message.SkillProto.ReqReleaseSkill getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqReleaseSkill>
        PARSER = new com.google.protobuf.AbstractParser<ReqReleaseSkill>() {
      @java.lang.Override
      public ReqReleaseSkill parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ReqReleaseSkill> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqReleaseSkill> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.whk.protobuf.message.SkillProto.ReqReleaseSkill getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResSkillMoveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResSkillMove)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Movement movement = 1;</code>
     * @return Whether the movement field is set.
     */
    boolean hasMovement();
    /**
     * <code>.Movement movement = 1;</code>
     * @return The movement.
     */
    com.whk.protobuf.message.SkillProto.Movement getMovement();
    /**
     * <code>.Movement movement = 1;</code>
     */
    com.whk.protobuf.message.SkillProto.MovementOrBuilder getMovementOrBuilder();

    /**
     * <code>int32 skillId = 2;</code>
     * @return The skillId.
     */
    int getSkillId();

    /**
     * <code>int64 ownerId = 3;</code>
     * @return The ownerId.
     */
    long getOwnerId();
  }
  /**
   * Protobuf type {@code ResSkillMove}
   */
  public static final class ResSkillMove extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResSkillMove)
      ResSkillMoveOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        ResSkillMove.class.getName());
    }
    // Use ResSkillMove.newBuilder() to construct.
    private ResSkillMove(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResSkillMove() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whk.protobuf.message.SkillProto.internal_static_ResSkillMove_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whk.protobuf.message.SkillProto.internal_static_ResSkillMove_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whk.protobuf.message.SkillProto.ResSkillMove.class, com.whk.protobuf.message.SkillProto.ResSkillMove.Builder.class);
    }

    private int bitField0_;
    public static final int MOVEMENT_FIELD_NUMBER = 1;
    private com.whk.protobuf.message.SkillProto.Movement movement_;
    /**
     * <code>.Movement movement = 1;</code>
     * @return Whether the movement field is set.
     */
    @java.lang.Override
    public boolean hasMovement() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Movement movement = 1;</code>
     * @return The movement.
     */
    @java.lang.Override
    public com.whk.protobuf.message.SkillProto.Movement getMovement() {
      return movement_ == null ? com.whk.protobuf.message.SkillProto.Movement.getDefaultInstance() : movement_;
    }
    /**
     * <code>.Movement movement = 1;</code>
     */
    @java.lang.Override
    public com.whk.protobuf.message.SkillProto.MovementOrBuilder getMovementOrBuilder() {
      return movement_ == null ? com.whk.protobuf.message.SkillProto.Movement.getDefaultInstance() : movement_;
    }

    public static final int SKILLID_FIELD_NUMBER = 2;
    private int skillId_ = 0;
    /**
     * <code>int32 skillId = 2;</code>
     * @return The skillId.
     */
    @java.lang.Override
    public int getSkillId() {
      return skillId_;
    }

    public static final int OWNERID_FIELD_NUMBER = 3;
    private long ownerId_ = 0L;
    /**
     * <code>int64 ownerId = 3;</code>
     * @return The ownerId.
     */
    @java.lang.Override
    public long getOwnerId() {
      return ownerId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getMovement());
      }
      if (skillId_ != 0) {
        output.writeInt32(2, skillId_);
      }
      if (ownerId_ != 0L) {
        output.writeInt64(3, ownerId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMovement());
      }
      if (skillId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, skillId_);
      }
      if (ownerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, ownerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.whk.protobuf.message.SkillProto.ResSkillMove)) {
        return super.equals(obj);
      }
      com.whk.protobuf.message.SkillProto.ResSkillMove other = (com.whk.protobuf.message.SkillProto.ResSkillMove) obj;

      if (hasMovement() != other.hasMovement()) return false;
      if (hasMovement()) {
        if (!getMovement()
            .equals(other.getMovement())) return false;
      }
      if (getSkillId()
          != other.getSkillId()) return false;
      if (getOwnerId()
          != other.getOwnerId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMovement()) {
        hash = (37 * hash) + MOVEMENT_FIELD_NUMBER;
        hash = (53 * hash) + getMovement().hashCode();
      }
      hash = (37 * hash) + SKILLID_FIELD_NUMBER;
      hash = (53 * hash) + getSkillId();
      hash = (37 * hash) + OWNERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOwnerId());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.whk.protobuf.message.SkillProto.ResSkillMove parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.SkillProto.ResSkillMove parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.ResSkillMove parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.SkillProto.ResSkillMove parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.ResSkillMove parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.SkillProto.ResSkillMove parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.ResSkillMove parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.whk.protobuf.message.SkillProto.ResSkillMove parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.whk.protobuf.message.SkillProto.ResSkillMove parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.whk.protobuf.message.SkillProto.ResSkillMove parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.ResSkillMove parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.whk.protobuf.message.SkillProto.ResSkillMove parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.whk.protobuf.message.SkillProto.ResSkillMove prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResSkillMove}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResSkillMove)
        com.whk.protobuf.message.SkillProto.ResSkillMoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whk.protobuf.message.SkillProto.internal_static_ResSkillMove_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whk.protobuf.message.SkillProto.internal_static_ResSkillMove_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whk.protobuf.message.SkillProto.ResSkillMove.class, com.whk.protobuf.message.SkillProto.ResSkillMove.Builder.class);
      }

      // Construct using com.whk.protobuf.message.SkillProto.ResSkillMove.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getMovementFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        movement_ = null;
        if (movementBuilder_ != null) {
          movementBuilder_.dispose();
          movementBuilder_ = null;
        }
        skillId_ = 0;
        ownerId_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whk.protobuf.message.SkillProto.internal_static_ResSkillMove_descriptor;
      }

      @java.lang.Override
      public com.whk.protobuf.message.SkillProto.ResSkillMove getDefaultInstanceForType() {
        return com.whk.protobuf.message.SkillProto.ResSkillMove.getDefaultInstance();
      }

      @java.lang.Override
      public com.whk.protobuf.message.SkillProto.ResSkillMove build() {
        com.whk.protobuf.message.SkillProto.ResSkillMove result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.whk.protobuf.message.SkillProto.ResSkillMove buildPartial() {
        com.whk.protobuf.message.SkillProto.ResSkillMove result = new com.whk.protobuf.message.SkillProto.ResSkillMove(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.whk.protobuf.message.SkillProto.ResSkillMove result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.movement_ = movementBuilder_ == null
              ? movement_
              : movementBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.skillId_ = skillId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.ownerId_ = ownerId_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whk.protobuf.message.SkillProto.ResSkillMove) {
          return mergeFrom((com.whk.protobuf.message.SkillProto.ResSkillMove)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whk.protobuf.message.SkillProto.ResSkillMove other) {
        if (other == com.whk.protobuf.message.SkillProto.ResSkillMove.getDefaultInstance()) return this;
        if (other.hasMovement()) {
          mergeMovement(other.getMovement());
        }
        if (other.getSkillId() != 0) {
          setSkillId(other.getSkillId());
        }
        if (other.getOwnerId() != 0L) {
          setOwnerId(other.getOwnerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMovementFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                skillId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                ownerId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.whk.protobuf.message.SkillProto.Movement movement_;
      private com.google.protobuf.SingleFieldBuilder<
          com.whk.protobuf.message.SkillProto.Movement, com.whk.protobuf.message.SkillProto.Movement.Builder, com.whk.protobuf.message.SkillProto.MovementOrBuilder> movementBuilder_;
      /**
       * <code>.Movement movement = 1;</code>
       * @return Whether the movement field is set.
       */
      public boolean hasMovement() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.Movement movement = 1;</code>
       * @return The movement.
       */
      public com.whk.protobuf.message.SkillProto.Movement getMovement() {
        if (movementBuilder_ == null) {
          return movement_ == null ? com.whk.protobuf.message.SkillProto.Movement.getDefaultInstance() : movement_;
        } else {
          return movementBuilder_.getMessage();
        }
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      public Builder setMovement(com.whk.protobuf.message.SkillProto.Movement value) {
        if (movementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          movement_ = value;
        } else {
          movementBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      public Builder setMovement(
          com.whk.protobuf.message.SkillProto.Movement.Builder builderForValue) {
        if (movementBuilder_ == null) {
          movement_ = builderForValue.build();
        } else {
          movementBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      public Builder mergeMovement(com.whk.protobuf.message.SkillProto.Movement value) {
        if (movementBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            movement_ != null &&
            movement_ != com.whk.protobuf.message.SkillProto.Movement.getDefaultInstance()) {
            getMovementBuilder().mergeFrom(value);
          } else {
            movement_ = value;
          }
        } else {
          movementBuilder_.mergeFrom(value);
        }
        if (movement_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      public Builder clearMovement() {
        bitField0_ = (bitField0_ & ~0x00000001);
        movement_ = null;
        if (movementBuilder_ != null) {
          movementBuilder_.dispose();
          movementBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      public com.whk.protobuf.message.SkillProto.Movement.Builder getMovementBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMovementFieldBuilder().getBuilder();
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      public com.whk.protobuf.message.SkillProto.MovementOrBuilder getMovementOrBuilder() {
        if (movementBuilder_ != null) {
          return movementBuilder_.getMessageOrBuilder();
        } else {
          return movement_ == null ?
              com.whk.protobuf.message.SkillProto.Movement.getDefaultInstance() : movement_;
        }
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.whk.protobuf.message.SkillProto.Movement, com.whk.protobuf.message.SkillProto.Movement.Builder, com.whk.protobuf.message.SkillProto.MovementOrBuilder> 
          getMovementFieldBuilder() {
        if (movementBuilder_ == null) {
          movementBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.whk.protobuf.message.SkillProto.Movement, com.whk.protobuf.message.SkillProto.Movement.Builder, com.whk.protobuf.message.SkillProto.MovementOrBuilder>(
                  getMovement(),
                  getParentForChildren(),
                  isClean());
          movement_ = null;
        }
        return movementBuilder_;
      }

      private int skillId_ ;
      /**
       * <code>int32 skillId = 2;</code>
       * @return The skillId.
       */
      @java.lang.Override
      public int getSkillId() {
        return skillId_;
      }
      /**
       * <code>int32 skillId = 2;</code>
       * @param value The skillId to set.
       * @return This builder for chaining.
       */
      public Builder setSkillId(int value) {

        skillId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 skillId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkillId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        skillId_ = 0;
        onChanged();
        return this;
      }

      private long ownerId_ ;
      /**
       * <code>int64 ownerId = 3;</code>
       * @return The ownerId.
       */
      @java.lang.Override
      public long getOwnerId() {
        return ownerId_;
      }
      /**
       * <code>int64 ownerId = 3;</code>
       * @param value The ownerId to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerId(long value) {

        ownerId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ownerId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ownerId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResSkillMove)
    }

    // @@protoc_insertion_point(class_scope:ResSkillMove)
    private static final com.whk.protobuf.message.SkillProto.ResSkillMove DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.whk.protobuf.message.SkillProto.ResSkillMove();
    }

    public static com.whk.protobuf.message.SkillProto.ResSkillMove getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResSkillMove>
        PARSER = new com.google.protobuf.AbstractParser<ResSkillMove>() {
      @java.lang.Override
      public ResSkillMove parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResSkillMove> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResSkillMove> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.whk.protobuf.message.SkillProto.ResSkillMove getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResReleaseSkillOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResReleaseSkill)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Movement movement = 1;</code>
     * @return Whether the movement field is set.
     */
    boolean hasMovement();
    /**
     * <code>.Movement movement = 1;</code>
     * @return The movement.
     */
    com.whk.protobuf.message.SkillProto.Movement getMovement();
    /**
     * <code>.Movement movement = 1;</code>
     */
    com.whk.protobuf.message.SkillProto.MovementOrBuilder getMovementOrBuilder();

    /**
     * <code>int32 skillId = 2;</code>
     * @return The skillId.
     */
    int getSkillId();

    /**
     * <code>int64 ownerId = 3;</code>
     * @return The ownerId.
     */
    long getOwnerId();

    /**
     * <code>int64 targetId = 4;</code>
     * @return The targetId.
     */
    long getTargetId();

    /**
     * <code>int64 damage = 5;</code>
     * @return The damage.
     */
    long getDamage();
  }
  /**
   * Protobuf type {@code ResReleaseSkill}
   */
  public static final class ResReleaseSkill extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ResReleaseSkill)
      ResReleaseSkillOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 1,
        /* suffix= */ "",
        ResReleaseSkill.class.getName());
    }
    // Use ResReleaseSkill.newBuilder() to construct.
    private ResReleaseSkill(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResReleaseSkill() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whk.protobuf.message.SkillProto.internal_static_ResReleaseSkill_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whk.protobuf.message.SkillProto.internal_static_ResReleaseSkill_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whk.protobuf.message.SkillProto.ResReleaseSkill.class, com.whk.protobuf.message.SkillProto.ResReleaseSkill.Builder.class);
    }

    private int bitField0_;
    public static final int MOVEMENT_FIELD_NUMBER = 1;
    private com.whk.protobuf.message.SkillProto.Movement movement_;
    /**
     * <code>.Movement movement = 1;</code>
     * @return Whether the movement field is set.
     */
    @java.lang.Override
    public boolean hasMovement() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Movement movement = 1;</code>
     * @return The movement.
     */
    @java.lang.Override
    public com.whk.protobuf.message.SkillProto.Movement getMovement() {
      return movement_ == null ? com.whk.protobuf.message.SkillProto.Movement.getDefaultInstance() : movement_;
    }
    /**
     * <code>.Movement movement = 1;</code>
     */
    @java.lang.Override
    public com.whk.protobuf.message.SkillProto.MovementOrBuilder getMovementOrBuilder() {
      return movement_ == null ? com.whk.protobuf.message.SkillProto.Movement.getDefaultInstance() : movement_;
    }

    public static final int SKILLID_FIELD_NUMBER = 2;
    private int skillId_ = 0;
    /**
     * <code>int32 skillId = 2;</code>
     * @return The skillId.
     */
    @java.lang.Override
    public int getSkillId() {
      return skillId_;
    }

    public static final int OWNERID_FIELD_NUMBER = 3;
    private long ownerId_ = 0L;
    /**
     * <code>int64 ownerId = 3;</code>
     * @return The ownerId.
     */
    @java.lang.Override
    public long getOwnerId() {
      return ownerId_;
    }

    public static final int TARGETID_FIELD_NUMBER = 4;
    private long targetId_ = 0L;
    /**
     * <code>int64 targetId = 4;</code>
     * @return The targetId.
     */
    @java.lang.Override
    public long getTargetId() {
      return targetId_;
    }

    public static final int DAMAGE_FIELD_NUMBER = 5;
    private long damage_ = 0L;
    /**
     * <code>int64 damage = 5;</code>
     * @return The damage.
     */
    @java.lang.Override
    public long getDamage() {
      return damage_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getMovement());
      }
      if (skillId_ != 0) {
        output.writeInt32(2, skillId_);
      }
      if (ownerId_ != 0L) {
        output.writeInt64(3, ownerId_);
      }
      if (targetId_ != 0L) {
        output.writeInt64(4, targetId_);
      }
      if (damage_ != 0L) {
        output.writeInt64(5, damage_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMovement());
      }
      if (skillId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, skillId_);
      }
      if (ownerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, ownerId_);
      }
      if (targetId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, targetId_);
      }
      if (damage_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, damage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.whk.protobuf.message.SkillProto.ResReleaseSkill)) {
        return super.equals(obj);
      }
      com.whk.protobuf.message.SkillProto.ResReleaseSkill other = (com.whk.protobuf.message.SkillProto.ResReleaseSkill) obj;

      if (hasMovement() != other.hasMovement()) return false;
      if (hasMovement()) {
        if (!getMovement()
            .equals(other.getMovement())) return false;
      }
      if (getSkillId()
          != other.getSkillId()) return false;
      if (getOwnerId()
          != other.getOwnerId()) return false;
      if (getTargetId()
          != other.getTargetId()) return false;
      if (getDamage()
          != other.getDamage()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMovement()) {
        hash = (37 * hash) + MOVEMENT_FIELD_NUMBER;
        hash = (53 * hash) + getMovement().hashCode();
      }
      hash = (37 * hash) + SKILLID_FIELD_NUMBER;
      hash = (53 * hash) + getSkillId();
      hash = (37 * hash) + OWNERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOwnerId());
      hash = (37 * hash) + TARGETID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTargetId());
      hash = (37 * hash) + DAMAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDamage());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.whk.protobuf.message.SkillProto.ResReleaseSkill prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResReleaseSkill}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResReleaseSkill)
        com.whk.protobuf.message.SkillProto.ResReleaseSkillOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whk.protobuf.message.SkillProto.internal_static_ResReleaseSkill_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whk.protobuf.message.SkillProto.internal_static_ResReleaseSkill_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.whk.protobuf.message.SkillProto.ResReleaseSkill.class, com.whk.protobuf.message.SkillProto.ResReleaseSkill.Builder.class);
      }

      // Construct using com.whk.protobuf.message.SkillProto.ResReleaseSkill.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getMovementFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        movement_ = null;
        if (movementBuilder_ != null) {
          movementBuilder_.dispose();
          movementBuilder_ = null;
        }
        skillId_ = 0;
        ownerId_ = 0L;
        targetId_ = 0L;
        damage_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whk.protobuf.message.SkillProto.internal_static_ResReleaseSkill_descriptor;
      }

      @java.lang.Override
      public com.whk.protobuf.message.SkillProto.ResReleaseSkill getDefaultInstanceForType() {
        return com.whk.protobuf.message.SkillProto.ResReleaseSkill.getDefaultInstance();
      }

      @java.lang.Override
      public com.whk.protobuf.message.SkillProto.ResReleaseSkill build() {
        com.whk.protobuf.message.SkillProto.ResReleaseSkill result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.whk.protobuf.message.SkillProto.ResReleaseSkill buildPartial() {
        com.whk.protobuf.message.SkillProto.ResReleaseSkill result = new com.whk.protobuf.message.SkillProto.ResReleaseSkill(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.whk.protobuf.message.SkillProto.ResReleaseSkill result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.movement_ = movementBuilder_ == null
              ? movement_
              : movementBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.skillId_ = skillId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.ownerId_ = ownerId_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.targetId_ = targetId_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.damage_ = damage_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whk.protobuf.message.SkillProto.ResReleaseSkill) {
          return mergeFrom((com.whk.protobuf.message.SkillProto.ResReleaseSkill)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.whk.protobuf.message.SkillProto.ResReleaseSkill other) {
        if (other == com.whk.protobuf.message.SkillProto.ResReleaseSkill.getDefaultInstance()) return this;
        if (other.hasMovement()) {
          mergeMovement(other.getMovement());
        }
        if (other.getSkillId() != 0) {
          setSkillId(other.getSkillId());
        }
        if (other.getOwnerId() != 0L) {
          setOwnerId(other.getOwnerId());
        }
        if (other.getTargetId() != 0L) {
          setTargetId(other.getTargetId());
        }
        if (other.getDamage() != 0L) {
          setDamage(other.getDamage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMovementFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                skillId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                ownerId_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                targetId_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                damage_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.whk.protobuf.message.SkillProto.Movement movement_;
      private com.google.protobuf.SingleFieldBuilder<
          com.whk.protobuf.message.SkillProto.Movement, com.whk.protobuf.message.SkillProto.Movement.Builder, com.whk.protobuf.message.SkillProto.MovementOrBuilder> movementBuilder_;
      /**
       * <code>.Movement movement = 1;</code>
       * @return Whether the movement field is set.
       */
      public boolean hasMovement() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.Movement movement = 1;</code>
       * @return The movement.
       */
      public com.whk.protobuf.message.SkillProto.Movement getMovement() {
        if (movementBuilder_ == null) {
          return movement_ == null ? com.whk.protobuf.message.SkillProto.Movement.getDefaultInstance() : movement_;
        } else {
          return movementBuilder_.getMessage();
        }
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      public Builder setMovement(com.whk.protobuf.message.SkillProto.Movement value) {
        if (movementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          movement_ = value;
        } else {
          movementBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      public Builder setMovement(
          com.whk.protobuf.message.SkillProto.Movement.Builder builderForValue) {
        if (movementBuilder_ == null) {
          movement_ = builderForValue.build();
        } else {
          movementBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      public Builder mergeMovement(com.whk.protobuf.message.SkillProto.Movement value) {
        if (movementBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            movement_ != null &&
            movement_ != com.whk.protobuf.message.SkillProto.Movement.getDefaultInstance()) {
            getMovementBuilder().mergeFrom(value);
          } else {
            movement_ = value;
          }
        } else {
          movementBuilder_.mergeFrom(value);
        }
        if (movement_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      public Builder clearMovement() {
        bitField0_ = (bitField0_ & ~0x00000001);
        movement_ = null;
        if (movementBuilder_ != null) {
          movementBuilder_.dispose();
          movementBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      public com.whk.protobuf.message.SkillProto.Movement.Builder getMovementBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMovementFieldBuilder().getBuilder();
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      public com.whk.protobuf.message.SkillProto.MovementOrBuilder getMovementOrBuilder() {
        if (movementBuilder_ != null) {
          return movementBuilder_.getMessageOrBuilder();
        } else {
          return movement_ == null ?
              com.whk.protobuf.message.SkillProto.Movement.getDefaultInstance() : movement_;
        }
      }
      /**
       * <code>.Movement movement = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.whk.protobuf.message.SkillProto.Movement, com.whk.protobuf.message.SkillProto.Movement.Builder, com.whk.protobuf.message.SkillProto.MovementOrBuilder> 
          getMovementFieldBuilder() {
        if (movementBuilder_ == null) {
          movementBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.whk.protobuf.message.SkillProto.Movement, com.whk.protobuf.message.SkillProto.Movement.Builder, com.whk.protobuf.message.SkillProto.MovementOrBuilder>(
                  getMovement(),
                  getParentForChildren(),
                  isClean());
          movement_ = null;
        }
        return movementBuilder_;
      }

      private int skillId_ ;
      /**
       * <code>int32 skillId = 2;</code>
       * @return The skillId.
       */
      @java.lang.Override
      public int getSkillId() {
        return skillId_;
      }
      /**
       * <code>int32 skillId = 2;</code>
       * @param value The skillId to set.
       * @return This builder for chaining.
       */
      public Builder setSkillId(int value) {

        skillId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 skillId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkillId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        skillId_ = 0;
        onChanged();
        return this;
      }

      private long ownerId_ ;
      /**
       * <code>int64 ownerId = 3;</code>
       * @return The ownerId.
       */
      @java.lang.Override
      public long getOwnerId() {
        return ownerId_;
      }
      /**
       * <code>int64 ownerId = 3;</code>
       * @param value The ownerId to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerId(long value) {

        ownerId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ownerId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ownerId_ = 0L;
        onChanged();
        return this;
      }

      private long targetId_ ;
      /**
       * <code>int64 targetId = 4;</code>
       * @return The targetId.
       */
      @java.lang.Override
      public long getTargetId() {
        return targetId_;
      }
      /**
       * <code>int64 targetId = 4;</code>
       * @param value The targetId to set.
       * @return This builder for chaining.
       */
      public Builder setTargetId(long value) {

        targetId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 targetId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTargetId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        targetId_ = 0L;
        onChanged();
        return this;
      }

      private long damage_ ;
      /**
       * <code>int64 damage = 5;</code>
       * @return The damage.
       */
      @java.lang.Override
      public long getDamage() {
        return damage_;
      }
      /**
       * <code>int64 damage = 5;</code>
       * @param value The damage to set.
       * @return This builder for chaining.
       */
      public Builder setDamage(long value) {

        damage_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 damage = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDamage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        damage_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ResReleaseSkill)
    }

    // @@protoc_insertion_point(class_scope:ResReleaseSkill)
    private static final com.whk.protobuf.message.SkillProto.ResReleaseSkill DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.whk.protobuf.message.SkillProto.ResReleaseSkill();
    }

    public static com.whk.protobuf.message.SkillProto.ResReleaseSkill getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResReleaseSkill>
        PARSER = new com.google.protobuf.AbstractParser<ResReleaseSkill>() {
      @java.lang.Override
      public ResReleaseSkill parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ResReleaseSkill> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResReleaseSkill> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.whk.protobuf.message.SkillProto.ResReleaseSkill getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Movement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Movement_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqReleaseSkill_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqReleaseSkill_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResSkillMove_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResSkillMove_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResReleaseSkill_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ResReleaseSkill_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Skill.proto\"+\n\010Movement\022\t\n\001x\030\001 \001(\005\022\t\n\001" +
      "y\030\002 \001(\005\022\t\n\001z\030\003 \001(\005\"\"\n\017ReqReleaseSkill\022\017\n" +
      "\007skillId\030\001 \001(\005\"M\n\014ResSkillMove\022\033\n\010moveme" +
      "nt\030\001 \001(\0132\t.Movement\022\017\n\007skillId\030\002 \001(\005\022\017\n\007" +
      "ownerId\030\003 \001(\003\"r\n\017ResReleaseSkill\022\033\n\010move" +
      "ment\030\001 \001(\0132\t.Movement\022\017\n\007skillId\030\002 \001(\005\022\017" +
      "\n\007ownerId\030\003 \001(\003\022\020\n\010targetId\030\004 \001(\003\022\016\n\006dam" +
      "age\030\005 \001(\003B&\n\030com.whk.protobuf.messageB\nS" +
      "killProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Movement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Movement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Movement_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_ReqReleaseSkill_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReqReleaseSkill_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReqReleaseSkill_descriptor,
        new java.lang.String[] { "SkillId", });
    internal_static_ResSkillMove_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResSkillMove_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResSkillMove_descriptor,
        new java.lang.String[] { "Movement", "SkillId", "OwnerId", });
    internal_static_ResReleaseSkill_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ResReleaseSkill_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ResReleaseSkill_descriptor,
        new java.lang.String[] { "Movement", "SkillId", "OwnerId", "TargetId", "Damage", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
